# -*- coding: utf-8 -*-
ESP = "Interassistenciologia"
A = "[[interassistencialidade]]"
def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "abridor-de-caminho": dac("Escritologia",640,"A escrita é processamento, técnica e *abridor de caminhos* para o Ser Humano: antes da escrita os fatos ocorriam; com a escrita os fatos começaram a acontecer."),
 "acabativa-interassistencial": lo("Acabativa",47,"*Acabativa: ponto final.* A acabativa de algo útil é sempre mais bela do que a iniciativa."),
 "acompanhante-parapsiquico": lo("Solidão",1852,"A pessoa excessivamente isolada tem, no mínimo, algum assediador extrafísico na condição de acompanhante."),
 "amparador-extrafisico": lo("Interassistencialidade",1078,"O *amparador extrafísico* ajuda à conscin tenepessista; a conscin tenepessista também ajuda ao amparador extrafísico."),
 "assistencia-do-assistido": lo("Assistência",154,"O **limite** para a assistência interconsciencial é a falta de afinidade com os megatrafares do assistido; quem exige mais assistência é quem não quer ser assistido."),
 "assistencia-inegoica": lo("Assistência",152,"A assistência, a assistência, sempre a **assistência interconsciencial** — feita sem ego."),
 "assistencia-sem-retorno": lo("Tacon",1886,"Na esfera da tacon, quem espera retorno não faz assistência, mas **negocinho.**"),
 "assistido-insatisfazivel": lo("Insatisfazível",1061,"**Pessoa insatisfazível** é aquela que quando tem *espaço* quer tempo, e quando tem *tempo* quer espaço."),
 "ataque-paraterapeutico": lo("Ataque",169,"O ataque extrafísico paraterapêutico é **paracirurgia de emergência** — promoção instantânea da metamorfose do *gorila extrafísico* em ser angelical."),
 "atitude-pro-amparador-extrafisico": src("Homo sapiens reurbanisatus","hsr","cap. 307",799,"O materpensene do leitor é pró-amparador ou pró-assediador?"),
 "autodemissao-de-consciex": lo("Consciex",499,"A consciex lúcida tem a capacidade de empregar os **megacons** de maneira teática, mais do que a conscin."),
 "beneficencia": lo("Beneficência",338,"*A beneficência alegra.*"),
 "categoria-da-minipeca-interassistencial": lo("Minipeça",1304,"Quanto mais a **conscin minipeça** se torna lúcida sobre o trabalho interassistencial, mais é comandada/teleguiada pelo Maximecanismo Multidimensional Interassistencial."),
 "chispa-discernidora": lo("Assistencialidade",157,"A **melhor assistência** interconsciencial é a intelectual discernidora."),
 "consciencia-assistente": lo("Assistente",163,"A **conscin assistente** minimiza os efeitos da *Lei de Causa e Efeito* sobre a consciência assistida."),
 "conscin-nao-intermissivista": lo("Intermissivista",1093,"A **conscin intermissivista** não tende a ser autista ou solitária, nem tem o direito de ser intelectual míope."),
 "conscin-tenepessavel": lo("Conscin",500,"*Conscin: lição ambulante.*"),
 "cuidadologia": lo("Cuidadologia",563,"*A falta de cuidado é a pior ignorância.* Não existe inteligência assentada sem a Autoprospectivologia."),
 "entrevista-interassistencial": src("Homo sapiens pacificus","hsp","cap. 379",972,"O clima interconsciencial dos mais avançados é constituído pela entrevista (projeção-entrevista) do pré-serenão com o Serenão."),
 "escala-interassistencial": lo("Tenepessista",1921,"A **conscin tenepessista** lúcida sabe, intimamente, qual o seu exato nível na Escala Evolutiva das Consciências, pela desenvoltura na multidimensionalidade interassistencial."),
 "evolucao-tacon-tares": lo("Tacon",1886,"A *tacon* é terapêutica ambulatorial; a **tares** é terapêutica cirúrgica."),
 "hiperacuidade-interassistencial": lo("Hiperacuidade",958,"*Hiperacuidade: memória dedutiva.* A hiperacuidade é o melhor molho da autopensenidade."),
 "holopensene-interassistencial": lo("Holopensene",974,"Quanto mais hígido o holopensene, mais radical do ponto de vista da racionalidade mentalsomática, evolutiva, cosmoética, interassistencial."),
 "incubadora-paratecnologica": lo("Holociclo",968,"O **holociclo** é *show room* da multidimensionalidade, megalaboratório de desassédio mentalsomático, fábrica de neossinapses e incubadora paratecnológica."),
 "intervencao-extrafisica": lo("Assistencialidade",158,"A **assistência cirúrgica** tem repercussão extrafísica maior — do placebo à intervenção cirúrgica."),
 "inversao-interassistencial": src("700 Experimentos da Conscienciologia","700exp","cap. 625",689,"A vida intrafísica compõe-se de 4 inversões conscienciais: a existencial, a assistencial, a da maturidade e a das ECs."),
 "minipeca-interassistencial": lo("Minipeça",1304,"Ser minipeça simples do Maximecanismo Multidimensional Interassistencial é factível à conscin intermissivista, mas ser **minipeça engraxada** e polida é mais difícil."),
 "nivel-da-interassistencialidade": lo("Interassistencialidade",1078,"O êxito da interassistencialidade depende do nível de entropia ou harmonia entre a consciência assistida e a assistente; quem comanda a solução é a personalidade assistente."),
 "oportunidade-de-ajudar": lo("Assistência",151,"Se você tentou ajudar a alguém e não conseguiu, aguarde, pois não faltará **oportunidade**: quem na assistência porfia, sorri de noite e de dia."),
 "parapreceptoria": lo("Parapreceptoria",1479,"A parapreceptoria exercida na dimenin é treinamento para a função de ***evoluciólogo*** na dimenex."),
 "perfil-assistencial": dac("Autoperfilologia",399,"Para fazer assistência interconsciencial é necessário diferentes facetas da polivalência, dependendo da categoria da assistência e do perfil do líder assistencial."),
 "pre-mae": lo("Pré-Mãe",1613,"A condição da pré-mãe, na Pré-Maternologia, corresponde à **parturição do holossoma**, análoga à mãe biológica que promove a parturição do soma."),
 "pre-perdao-assistencial": lo("Perdão",1533,"Apenas perdoar nem sempre basta: é necessário o *follow-up* assistencial, o acompanhamento, na maioria dos casos no universo da Interassistenciologia."),
 "producao-do-esclarecimento": lo("Esclarecimento",751,"O exemplo teático do **esclarecimento** elimina a contenda, a demanda, o conflito, a competição e a rivalidade."),
 "ranque-assistencial": src("Homo sapiens reurbanisatus","hsr","cap. 82",239,"O arrimo interconsciencial assistencial gera a *escala da lotação assistencial* da pessoa, dentro da escala evolutiva."),
 "retrofuncao-do-amparador": lo("Amparador",98,"Quanto mais você souber da **holobiografia** do seu amparador extrafísico, melhor para ambos."),
 "tares-expositiva": lo("Exposição",831,"A minitertúlia conscienciológica é **tribuna** expositiva."),
 "olhar-de-fraternidade": lo("Olhar",1390,"Evoluir é **saber olhar**, enxergando o essencial ou o prioritário evolutivo."),
 "minitares": src("Homo sapiens pacificus","hsp","cap. 398",1007,"A partir da Assistenciologia, as práticas diárias da tenepes geram condições evoluídas nas tarefas da antitransmigração interplanetária (anticonflitividade etc.)."),
}
CONV = {k:v for k,v in CONV.items() if v}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "abridor-de-caminho": R("quem abre o caminho assistencial","[[consciencia-assistente]] · [[producao-do-esclarecimento]]"),
 "acabativa-interassistencial": R("terminar o iniciado na assistência","[[producao-do-esclarecimento]] · [[subtarefa-relevante]]"),
 "acompanhante-parapsiquico": R("consciex que acompanha a conscin","[[amparador-extrafisico]] · [[paraconexao]]"),
 "amparador-extrafisico": R("consciex benfazeja auxiliadora","[[retrofuncao-do-amparador]] · [[parapreceptoria]] · [[atitude-pro-amparador-extrafisico]]"),
 "assistencia-do-assistido": R("reação assistencial do próprio assistido","[[assistido-insatisfazivel]] · [[nivel-da-interassistencialidade]]"),
 "assistencia-inegoica": R("assistência sem ego","[[assistencia-sem-retorno]] · [[beneficencia]]"),
 "assistencia-realista": R("assistência fundada na necessidade real","[[nivel-da-interassistencialidade]] · [[assistencia-do-assistido]]"),
 "assistencia-sem-retorno": R("assistir sem esperar retorno","[[assistencia-inegoica]] · [[beneficencia]]"),
 "assistido-insatisfazivel": R("assistido impossível de satisfazer","[[assistencia-do-assistido]] · [[limite-interassistencial]]"),
 "ataque-paraterapeutico": R("assédio fugaz permitido pelos amparadores","[[amparador-extrafisico]] · [[intervencao-extrafisica]]"),
 "atitude-pro-amparador-extrafisico": R("postura cosmoética a favor do amparo","[[amparador-extrafisico]] · [[retrofuncao-do-amparador]]"),
 "autodemissao-de-consciex": R("paraefeito do amparador demitente","[[amparador-extrafisico]] · [[retrofuncao-do-amparador]]"),
 "automegatrafarismo": R("consréu/conscin com megatrafares","[[ataque-paraterapeutico]] · [[assistido-insatisfazivel]]"),
 "beneficencia": R("trafor de fazer o bem","[[assistencia-inegoica]] · [[megadoacao]]"),
 "categoria-da-minipeca-interassistencial": R("predicamento da minipeça assistencial","[[minipeca-interassistencial]] · [[ranque-assistencial]]"),
 "chispa-discernidora": R("neoideia interassistencial incandescente","[[producao-do-esclarecimento]] · [[hiperacuidade-interassistencial]]"),
 "consciencia-assistente": R("conscin/consciex que ajuda","[[perfil-assistencial]] · [[abridor-de-caminho]]"),
 "conscin-nao-intermissivista": R("conscin sem CI cursado","[[conscin-tenepessavel]] · [[nivel-da-interassistencialidade]]"),
 "conscin-tenepessavel": R("adulto apto à tenepes","[[conscin-nao-intermissivista]] · [[retrospectiva-cosmoetica]]"),
 "cuidadologia": R("ciência do cuidado","[[consciencia-assistente]] · [[beneficencia]]"),
 "entrevista-interassistencial": R("mudar o ataque assediador em interação","[[ataque-paraterapeutico]] · [[intervencao-extrafisica]]"),
 "escala-interassistencial": R("hierarquia dos assistentes","[[ranque-assistencial]] · [[nivel-da-interassistencialidade]]"),
 "evolucao-tacon-tares": R("desenvolvimento tacon→tares","[[tacon]] · [[tares]] · [[producao-do-esclarecimento]]"),
 "hiperacuidade-interassistencial": R("hiperacuidade aplicada à assistência","[[chispa-discernidora]] · [[producao-do-esclarecimento]]"),
 "holopensene-interassistencial": R("atmosfera da interassistência","[[incubadora-paratecnologica]] · [[tempo-assistencial]]"),
 "incubadora-paratecnologica": R("holopensene de empreendimentos verponológicos","[[holopensene-interassistencial]]"),
 "intervencao-extrafisica": R("intervir via consciex amparadora","[[ataque-paraterapeutico]] · [[amparador-extrafisico]]"),
 "inversao-interassistencial": R("troca de posição amparador↔assistido","[[tempo-assistencial]] · [[escala-interassistencial]]"),
 "limite-interassistencial": R("raia da assistência possível","[[assistencia-do-assistido]] · [[assistido-insatisfazivel]]"),
 "megadoacao": R("doar amplamente em favor de outrem","[[beneficencia]] · [[assistencia-sem-retorno]]"),
 "megapolinomio-interassistencial": R("união de realidades interassistenciais","[[minipeca-interassistencial]] · [[nivel-da-interassistencialidade]]"),
 "minipeca-interassistencial": R("conscin lúcida do Maximecanismo","[[categoria-da-minipeca-interassistencial]] · [[maximecanismo]] · [[ranque-assistencial]]"),
 "minitares": R("tares executada de modo reduzido","[[tares-expositiva]] · [[producao-do-esclarecimento]]"),
 "mitoclastia": R("destruir mitos e ilusões","[[producao-do-esclarecimento]] · [[chispa-discernidora]]"),
 "nivel-da-interassistencialidade": R("patamar da assistência prestada","[[escala-interassistencial]] · [[assistencia-realista]]"),
 "olhar-de-fraternidade": R("olhar fraterno na assistência","[[megafraternidade]] · [[beneficencia]]"),
 "oportunidade-de-ajudar": R("ensejo de assistir","[[tempo-assistencial]] · [[beneficencia]]"),
 "paraconexao": R("ligação interconsciencial prévia","[[acompanhante-parapsiquico]] · [[amparador-extrafisico]]"),
 "parapreceptoria": R("paratares dos amparadores (treino de evoluciólogo)","[[amparador-extrafisico]] · [[producao-do-esclarecimento]]"),
 "perfil-assistencial": R("traços que tornam alguém assistente","[[consciencia-assistente]] · [[categoria-da-minipeca-interassistencial]]"),
 "pre-mae": R("parturição do holossoma (cobaia parapsíquica)","[[acompanhante-parapsiquico]] · [[paraconexao]]"),
 "pre-perdao-assistencial": R("perdoar antecipadamente para assistir","[[olhar-de-fraternidade]] · [[assistencia-inegoica]]"),
 "producao-do-esclarecimento": R("consecução da tares","[[tares]] · [[tares-expositiva]] · [[minitares]]"),
 "ranque-assistencial": R("posição na hierarquia assistencial","[[escala-interassistencial]] · [[categoria-da-minipeca-interassistencial]]"),
 "retrofuncao-do-amparador": R("função prévia do amparador na vida humana","[[amparador-extrafisico]] · [[autodemissao-de-consciex]]"),
 "retrospectiva-cosmoetica": R("revisão autocrítica diária do tenepessista","[[conscin-tenepessavel]] · [[tenepes]]"),
 "subtarefa-relevante": R("função da minipeça no maximecanismo","[[minipeca-interassistencial]] · [[acabativa-interassistencial]]"),
 "tara-parapsiquica": R("talento de suportar o peso assistencial","[[acompanhante-parapsiquico]] · [[perfil-assistencial]]"),
 "tares-expositiva": R("tares espontânea expositiva","[[producao-do-esclarecimento]] · [[minitares]]"),
 "tempo-assistencial": R("ocasião adequada da assistência","[[oportunidade-de-ajudar]] · [[inversao-interassistencial]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
