# -*- coding: utf-8 -*-
ESP = "Comunicologia"
A = "[[tares]]"
def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "alexitimia": src("Projeciologia","proj","cap. 318",636,"Peter Sifneos cunhou *alexitimia* para a condição de pessoas com falta de vocabulário adequado para expressar os próprios sentimentos."),
 "altofalante": lo("Autexemplo",189,"O **autexemplo** fala mais alto pelo silêncio do que pelo altofalante."),
 "antidogmatica": lo("PD",1515,"A Neociência Conscienciológica é a antirreligiosidade, a antigenuflexão, a **antidogmática**, a antirrepressão e a antilavagem subcerebral."),
 "antonimo": lo("Cara",378,"*Máscara* é o antônimo de **cara.**"),
 "argumentacao-ilogica": lo("Argumentação",136,"O objetivo da argumentação é o **esclarecimento** universal; em bases cosmoéticas e factuais, ajuda mais."),
 "associacao-didatica": lo("Evoluciólogo",808,"O evoluciólogo não faz somente associação de ideias, ele promove a **associação de consciências.**"),
 "autexpressao": dac("Timbrologia",1406,"Para melhorar a racionalização da autexpressão importa falar fino quando preciso e grosso quando as circunstâncias exigirem."),
 "autoconsciencia-verbal": dac("Circunloquiologia",492,"As circunlocuções têm metáforas técnicas como o *afogamento da ideia* em palavras e a *circunvagação lexical* (tortuosidade verbal, autodispersão)."),
 "banana-technique": lo("Mão",1217,"A mão da *banana technique* é processo impactoterápico no universo da *tarefa do esclarecimento* (tares)."),
 "categoria-de-comunicacao": lo("Paracerebrologia",1444,"Toda categoria de **comunicação interconsciencial**, mesmo interdimensional, ocorre sempre de paracérebro a paracérebro."),
 "citaciologia": dac("Escritologia",641,"A Citaciologia é uma das 15 variáveis da Conformática (Ciência do conteúdo e da forma) no universo da escrita."),
 "comunicacao-modular": lo("Comunicação",463,"A comunicação é básica no Cosmos; na dimenin, a comunicação mais relevante é a **escrita.**"),
 "conformatica": src("Homo sapiens pacificus","hsp","cap. 34",138,"O *confor* (conteúdo + forma) é variável da Conscienciologia, em relação direta com a Comunicologia (Conformática)."),
 "consciencia-grafica": src("700 Experimentos da Conscienciologia","700exp","cap. 62",126,"A Cosmoeticologia fornece, ao escrever, a pergunta de alto autodiscernimento: — Terei vergonha deste texto na próxima década?"),
 "conscienciografia": lo("Conscienciografia",486,"A facilidade para escrever é uma **responsabilidade policármica**; toda redação pessoal é, em tese, autobiográfica."),
 "enumerologia": dac("Enumerologia",623,"A Enumerologia classifica-se em duas categorias básicas: Enumerologia Horizontal e Enumerologia Vertical."),
 "expressao-facial": lo("Síntese",1842,"A **expressão facial** é a primeira síntese comunicativa da conscin na intrafisicalidade."),
 "ferramenta-de-comunicacao": lo("Ferramenta",870,"A ferramenta mais valiosa para o Ser Humano é a **autopensenidade.**"),
 "frase-enfatica": src("Homo sapiens reurbanisatus","hsr","cap. 49",132,"A *técnica da frase enfática* realça a importância de um enunciado por recurso léxico, sintático ou fonológico, tornando-o marcante e claro."),
 "gancho-didatico": lo("Gancho",901,"O gancho mnemônico, por meio de vocábulo ou frase antiga, pode desencadear autorretrocognições nítidas de existência humana anterior."),
 "holotecologia": dac("Holotecologia",771,"O maior efeito da leitura é o ato derivado bem feito. *Onirismo: lazer extrafísico. Leitura: lazer intrafísico.*"),
 "informacao-conscienciologica": src("200 Teáticas da Conscienciologia","200teat","cap. 106",126,"Em comunicologia, a *informação conscienciológica* baseia-se nos princípios da consciência integral, do holossoma, da multidimensionalidade e da multiexistencialidade."),
 "jornalismo-marrom": src("Homo sapiens pacificus","hsp","cap. 270",767,"As câmeras ocultas dos espiões da imprensa geraram os *jornalistas-espiões*, novas expressões do jornalismo sensacionalista e da imprensa marrom."),
 "linguagem-denotativa": lo("Linguagem",1177,"Sem *linguagem* não há **comunicação**; a linguagem materializa o autopensene."),
 "linguagem-mentalsomatica": src("Projeciologia","proj","cap. 269",542,"A linguagem nativa da dimensão mentalsomática é o *conscienciês.*"),
 "matematizacao-do-conceito": src("700 Experimentos da Conscienciologia","700exp","cap. 700",764,"A *Fórmula Ideal da Conscienciologia* indica a matematização prática possível da consciência."),
 "modelo-mentalsomatico": src("200 Teáticas da Conscienciologia","200teat","cap. 32",52,"Pela holomaturologia, o Serenão é tomado como modelo e exemplo evolutivo — depois dele caminhamos com os mentaissomas na obscuridade espessa."),
 "mutualidade-da-comunicacao": lo("Mutualidade",1336,"Os **parceiros da dupla evolutiva** dependem sempre um do outro: a perna ferida impede o exercício da perna sã."),
 "nomadismo-consciencial": src("Projeciologia","proj","cap. 494",943,"O nomadismo consciencial voluntário, cosmoético e interassistencial é o instrumento mais eficaz pelo qual as projeções lúcidas anulam a necessidade de a consciex ressomar."),
 "orismologia": lo("Orismologia",1411,"A **Orismologia** (Terminologia mais técnica) objetiva eliminar a vacuidade dos pensamentos; quem a combate tem medo dos conteúdos das palavras."),
 "palavra-chave": lo("Palavras",1433,"Sopese todas as palavras e valorize a **palavra-chave.**"),
 "palavra": lo("Palavra",1431,"*Palavra: veste pensênica.* A palavra que ensina não magoa; cada palavra tem a sua força."),
 "proverbio-mundial": lo("Provérbio",1660,"*Provérbio: vox populi. Provérbio: herança experimental.*"),
 "publico-alvo-conscienciologico": lo("Público-alvo",1671,"O melhor público-alvo dos trabalhos interassistenciais reúne as consciências contemporâneas e as da posteridade."),
 "sinonimo": lo("Sinônimos",1841,"*Guerra é sinônimo de derrota. Paz é sinônimo de vitória.*"),
 "sinonimologia": lo("Sinonimologia",1841,"O uso cotidiano das sinonímias leva à precisão da expressividade pessoal, oral e escrita — nenhuma palavra é igual a outra."),
 "tecnica-dos-atos-fatos-parafatos": lo("Fatos",860,"Diálogos, debates e argumentações só têm valor se fundamentados na lógica dos **fatos e parafatos.**"),
 "verbetorado-conscienciologico": lo("Verbetografia",1996,"O **verbetorado** fixa o processo evolutivo da Reurbexologia."),
 "enumerologia2": None,
 "antonimologia": dac("Escritologia",641,"A Antonimologia é a 1ª das 15 variáveis relevantes da Conformática (Ciência do conteúdo e da forma) na escrita."),
 "tecnica-da-qualificacao-dos-verbetes": src("Homo sapiens reurbanisatus","hsr","cap. 83",139,"A *técnica da quantificação da qualidade* é o incremento paradoxal da quantidade dos constructos de melhor qualificação em qualquer comunicação."),
 "via-expressa-do-pensamento": src("Projeciologia","proj","cap. 431",824,"A projeção consciencial instantânea é a via expressa da conscin que se transfere momentaneamente para a dimensão extrafísica."),
}
CONV = {k:v for k,v in CONV.items() if v}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "alexitimia": R("incapacidade de verbalizar sentimentos","[[autexpressao]] · [[expressao-facial]]"),
 "altofalante": R("amplificação do som vs. autexemplo","[[ferramenta-de-comunicacao]] · [[autexpressao]]"),
 "antidogmatica": R("atitudes contra o dogma","[[orismologia]] · [[argumentacao-ilogica]]"),
 "antonimo": R("palavra de significação oposta","[[antonimologia]] · [[sinonimo]]"),
 "antonimologia": R("ciência dos antônimos","[[antonimo]] · [[sinonimologia]] · [[conformatica]]"),
 "argumentacao-ilogica": R("argumentar sem lógica dos fatos","[[tecnica-dos-atos-fatos-parafatos]] · [[exegese-conscienciologica]]"),
 "associacao-didatica": R("junção de termos que facilita compreensão","[[gancho-didatico]] · [[bloco-intelectivo]]"),
 "autexpressao": R("exteriorizar/comunicar para os outros","[[autoconsciencia-verbal]] · [[ferramenta-de-comunicacao]]"),
 "autoconsciencia-verbal": R("lucidez quanto à própria comunicação","[[autexpressao]] · [[linguagem-denotativa]]"),
 "banana-technique": R("gesto impactoterápico da tares","[[tares]]" if False else "[[expressao-facial]] · [[publico-alvo-conscienciologico]]"),
 "besteirol": R("tendência cultural pop de baixo teor","[[jornalismo-marrom]] · [[proverbio-mundial]]"),
 "bloco-intelectivo": R("composição de 7 elementos","[[associacao-didatica]] · [[enumerologia]]"),
 "categoria-de-comunicacao": R("tipo de comunicabilidade empregado","[[comunicacao-modular]] · [[linguagem-mentalsomatica]]"),
 "citaciologia": R("ciência do emprego da citação","[[conformatica]] · [[exegese-conscienciologica]]"),
 "cognato": R("palavra da mesma raiz etimológica","[[antonimo]] · [[sinonimo]]"),
 "comunicacao-modular": R("abordagens panorâmicas megabrangentes","[[categoria-de-comunicacao]] · [[modelo-mentalsomatico]]"),
 "conformatica": R("ciência do confor (conteúdo+forma)","[[citaciologia]] · [[antonimologia]] · [[sinonimologia]]"),
 "consciencia-grafica": R("autopensenização evoluída na escrita","[[conscienciografia]] · [[prioridade-da-escrita]]"),
 "conscienciografia": R("ciência de escrever sobre a Conscienciologia","[[consciencia-grafica]] · [[verbetorado-conscienciologico]] · [[prioridade-da-escrita]]"),
 "diferenca-semantica": R("divergência de significado","[[sinonimo]] · [[antonimo]]"),
 "divulgacao-cientifica": R("tornar públicos os princípios científicos","[[publico-alvo-conscienciologico]] · [[informacao-conscienciologica]]"),
 "edicao-gratuita": R("edição grátis do livro pelo autor","[[conscienciografia]] · [[publico-alvo-conscienciologico]]"),
 "elipse-informativa": R("supressão de termo/fonte","[[enumerologia]] · [[sublinhamento]]"),
 "enumerologia": R("ciência da enumeração de fatos","[[bloco-intelectivo]] · [[elipse-informativa]]"),
 "exegese-conscienciologica": R("comentário que interpreta/explica","[[citaciologia]] · [[argumentacao-ilogica]]"),
 "expressao-facial": R("síntese comunicativa do rosto","[[autexpressao]] · [[alexitimia]]"),
 "expressao-intercambiavel": R("constructo que compõe binômio","[[sinonimo]] · [[palavra-chave]]"),
 "extrapauta": R("ocorrência inesperada na rotina","[[informacao-conscienciologica]]"),
 "ferramenta-de-comunicacao": R("meio de exposição da autopensenidade","[[autexpressao]] · [[palavra]]"),
 "frase-enfatica": R("recurso que realça a importância","[[palavra-chave]] · [[titulo-provocador]]"),
 "gancho-didatico": R("citação de caso que ancora o ensino","[[associacao-didatica]] · [[bloco-intelectivo]]"),
 "hibridismo": R("cruzamento de palavras de raízes diversas","[[cognato]] · [[orismologia]]"),
 "holotecologia": R("ciência dos acervos da Holoteca","[[conscienciografia]] · [[verbete]]"),
 "informacao-conscienciologica": R("informe baseado na consciência integral","[[divulgacao-cientifica]] · [[comunicacao-modular]]"),
 "jornalismo-marrom": R("exercício antiético do jornalismo","[[besteirol]] · [[divulgacao-cientifica]]"),
 "linguagem-denotativa": R("termos na exata extensão dos conceitos","[[linguagem-mentalsomatica]] · [[orismologia]]"),
 "linguagem-mentalsomatica": R("comunicar ideias elevadas (conscienciês)","[[linguagem-denotativa]] · [[categoria-de-comunicacao]]"),
 "matematizacao-do-conceito": R("explicitação aritmética do conceito","[[modelo-mentalsomatico]] · [[bloco-intelectivo]]"),
 "modelo-mentalsomatico": R("fórmula padrão de comunicação","[[comunicacao-modular]] · [[matematizacao-do-conceito]]"),
 "mutualidade-da-comunicacao": R("reciprocidade autor-leitor","[[publico-alvo-conscienciologico]] · [[categoria-de-comunicacao]]"),
 "nomadismo-consciencial": R("consciência lúcida e errante","[[via-expressa-do-pensamento]] · [[linguagem-mentalsomatica]]"),
 "orismologia": R("ciência dos termos técnicos","[[sinonimologia]] · [[antonimologia]] · [[linguagem-denotativa]]"),
 "palavra-chave": R("traduz a síntese do contexto","[[palavra]] · [[frase-enfatica]] · [[titulo-provocador]]"),
 "palavra": R("unidade mínima da língua escrita","[[palavra-chave]] · [[sinonimo]] · [[linguagem-denotativa]]"),
 "prioridade-da-escrita": R("manter a escrita em primeiro lugar","[[conscienciografia]] · [[consciencia-grafica]]"),
 "proverbio-mundial": R("frase curta de sabedoria popular","[[gancho-didatico]] · [[palavra-chave]]"),
 "publico-alvo-conscienciologico": R("segmento a que se destina a mensagem","[[divulgacao-cientifica]] · [[mutualidade-da-comunicacao]]"),
 "sinonimo": R("palavra de significado semelhante","[[sinonimologia]] · [[antonimo]] · [[palavra]]"),
 "sinonimologia": R("ciência das vozes sinônimas","[[sinonimo]] · [[antonimologia]] · [[orismologia]]"),
 "sublinhamento": R("grifar/negritar para destacar","[[palavra-chave]] · [[elipse-informativa]]"),
 "tecnica-da-qualificacao-dos-verbetes": R("escolha qualimétrica dos constructos","[[verbete]] · [[verbete-chave]]"),
 "tecnica-do-crescendo": R("amplificação progressiva da ideia","[[frase-enfatica]] · [[bloco-intelectivo]]"),
 "tecnica-dos-atos-fatos-parafatos": R("triagem das sínteses por fatos/parafatos","[[argumentacao-ilogica]] · [[exegese-conscienciologica]]"),
 "titulo-provocador": R("título que provoca o leitor","[[palavra-chave]] · [[frase-enfatica]]"),
 "verbete-chave": R("verbete de destaque na Enciclopédia","[[verbete]] · [[tecnica-da-qualificacao-dos-verbetes]]"),
 "verbete": R("entrada definidora da Enciclopédia","[[verbete-chave]] · [[verbetorado-conscienciologico]]"),
 "verbetorado-conscienciologico": R("função/título do verbetógrafo","[[verbete]] · [[conscienciografia]]"),
 "via-expressa-do-pensamento": R("meio metódico de exteriorizar o pensamento","[[ferramenta-de-comunicacao]] · [[nomadismo-consciencial]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
