# -*- coding: utf-8 -*-
ESP = "Evoluciologia"
A = "[[evoluciologia]]"

def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "abertismo-consciencial": lo("Abertismo",42,"Não se pode fazer assistência de alta expressão sem o abertismo consciencial; ele tem o limite de não nos tornar cúmplices de atos anticosmoéticos."),
 "aceleracao-da-historia-pessoal": lo("História",964,"A *Era da Aceleração da História*, própria da Reurbanologia, é expressa pela troca do carro de bois pela astronave, a caminho do Estado Mundial."),
 "agente-desencadeador": lo("Assistível",166,"Não é o **evoluciólogo** o agente desencadeador que mais dinamiza a evolução de alguém, mas a consciência assistível, em si."),
 "andaime-consciencial": lo("Construção",508,"O período intermissivo da consciex é o *andaime*; a vida intrafísica da conscin é a **construção evolutiva.**"),
 "antissubumanidade": src("Homo sapiens pacificus","hsp","cap. 12",585,"Os vocábulos *antissubumanidade* e *antissubumano* são neologismos técnicos da Evoluciologia."),
 "aparecimento-dos-evoluciologos": lo("Evoluciólogos",808,"O Planeta Terra, pela Pararreurbanologia, prepara-se para conviver com a presença ostensiva dos Seres Serenões — a primeira manifestação será o surgimento pessoal dos evoluciólogos."),
 "atrator": lo("Atratibilidade",176,"- \"Você, conscin intermissivista, querendo ou não, é atrator, mas resta questionar-se: atrator de quê?\""),
 "autevolucao": lo("Autevolução",187,"*Autevolução: modéstia acumulada.* A vida humana é breve, a autevolução é perene."),
 "autopotencializacao": dac("Autopotencializaciologia",403,"A reação de lucidez maior surge paradoxal — parece concentrar-se no egocarma, saindo do grupocarma — mas as autorreflexões maiores reposicionam a conscin no policarma."),
 "autopromocao-evolutiva": lo("Compléxis",450,"*Compléxis é autopromoção.*"),
 "colheita-intermissiva": lo("Frutos",892,"Os frutos do seu **trabalho evolutivo** de hoje, além da colheita intermissiva, serão colhidos a partir da próxima vida humana, a real estação da colheita."),
 "colheita-intrafisica": src("Manual da Proéxis","proexis","cap. 23",94,"Na fase de execução da proéxis, a conscin-madura (hiperacuidade) trabalha na *desova* de seus frutos intelectuais, com 90% de recursos próprios."),
 "compassageiro-evolutivo": lo("Mar",1219,"Há o **compassageiro evolutivo** igual ao mar: lindo, porém não se pode confiar."),
 "consciencia-podalica": src("200 Teáticas da Conscienciologia","200teat","cap. 42",62,"A consciência podálica (ou consciência-guepardo) prioriza os pés no emprego do soma, vivendo sob o monopólio das pernas."),
 "consciex-livre": lo("CL",417,"***Consciex Livre*** (CL) é sinônimo de *Consciex Galáctica*; a consciex da Comunex Evoluída aplica o livre-arbítrio mais perfeito."),
 "continuismo-consciencial": src("200 Teáticas da Conscienciologia","200teat","cap. 51",71,"Pela despertologia, o *desligamento* consciencial (alienação) é um trafar; já o *continuísmo* consciencial é um trafor."),
 "crise-pessoal": src("Homo sapiens pacificus","hsp","cap. 279",781,"Sob a ótica da Evoluciologia, a crise é elemento básico em toda escala de estressamento humano, surgindo em momentos cruciais do destino da conscin."),
 "diferencial-da-conscienciologia": lo("Conscienciologia",495,"A Ciência que pesquisa a Paraprocedenciologia, no universo da Parassociologia Multidimensional, é o primeiro indicador diferencial da Conscienciologia para com as Ciências Convencionais."),
 "elo": dac("Holoeutimiologia",757,"A conscin intermissivista é o elo da corrente evolutiva da Conscienciologia. Você é um elo fraco ou forte dessa corrente?"),
 "ensino": lo("Ensino",724,"*Ensino: estímulo evolutivo.* O ensino máximo que existe é fazer o que se diz."),
 "epicon-lucido": src("Homo sapiens reurbanisatus","hsr","cap. 65",198,"Epicon Lúcido (Homo sapiens epicentricus) corresponde a cerca de 35% do Serenão na escala da semiconsciexialidade."),
 "epiconscienciologia": dac("Autocosmoconscienciologia",279,"Existe o *megatrinômio Autocosmoconscienciologia-Serenologia-Consciex Livre* (Epiconscienciologia)."),
 "equivalencia-evolutiva": lo("Equivalência",740,"A mãe do genocida e a do criador da metralhadora se equivalem no caminho da **evolução grupocármica.**"),
 "escala-da-consciencia-continua": src("700 Experimentos da Conscienciologia","700exp","cap. 468",532,"A Conscienciologia aborda o estado da consciência contínua numa escala de 7 estágios de lucidez: Provas, Impacto, Admissão, Ética, Filiação, Sutilização, Purificação."),
 "escala-das-prioridades-evolutivas": lo("Prioridades",1628,"Os **parapreceptores evolutivos** cosmoéticos jamais adulam, mas ensinam as prioridades máximas, evolutivas, teáticas."),
 "evolucao-agonistica": lo("Evolução",796,"*Evolução é atividade. Evolução é interassistência.*"),
 "evoluciologo": lo("Evoluciólogo",806,"*Evoluciólogo: condutor consciencial. Evoluciólogo: magistrado evolutivo.*"),
 "extrapolacionismo": lo("Extrapolacionismo",836,"*Extrapolacionismo: teste parafenomênico.* O extrapolacionismo parapsíquico é o **exopensene do futuro.**"),
 "gargalo-evolutivo": lo("Gargalologia",902,"Chega-se à passagem inevitável de todo gargalo evolutivo por meio da **persistência.**"),
 "gestacao-evolutiva": src("200 Teáticas da Conscienciologia","200teat","cap. 90",110,"Em proexologia, a gestação consciencial é a produtividade evolutiva, útil, da consciência humana, no quadro de obras da sua proéxis."),
 "hermeneutica-da-evoluciologia": lo("Para-Hermenêutica",1464,"A compreensão da Para-Hermenêutica somente ocorre, de fato, com a autocosmovisão e o autoparapsiquismo."),
 "holomaturologia": src("Homo sapiens pacificus","hsp","cap. 57",190,"A Holomaturologia é subcampo científico da Evoluciologia."),
 "inocencia": lo("Inocência",1060,"Em certos contingenciamentos, a *inocência* é sinônimo de **ignorância.**"),
 "know-how-evolutivo": lo("Know-how",1139,"O ***know-how* evolutivo** é o *modus operandi* da conscin lúcida perante a evolução, a partir da autovivência teática da Inteligência Evolutiva (IE)."),
 "liberologia": dac("Modismologia",1013,"No âmbito da Socin Patológica, temos de nos libertar de todas as raias coercitivas que agem sobre nós, a fim de termos liberdade de manifestação evolutiva."),
 "maxidissidente-coadjutor": lo("Maxidissidente",1230,"Em geral, o **maxidissidente** é a pessoa divisionista que caminha à frente do partido para o universalismo da fraternidade pura."),
 "maximologia-evolutiva": dac("Maximologia",904,"Em face dos ângulos críticos da Maximologia Pessoal evoluída, a consciência lúcida insere-se em algum dos 7 patamares da Escala Evolutiva das Consciências."),
 "megaparadoxo-evolutivo": lo("Megaparadoxo",1259,"Um **megaparadoxo** governa a vida: a consciência mais livre é a mais submissa à Cosmoética."),
 "megatolice": lo("Megatolice",1269,"A **megatolice** mais trágica do Tolicionário Humano é o ato de substituir a razão da mente pela violência dos bíceps."),
 "microminoria-evolutiva": src("Homo sapiens reurbanisatus","hsr","cap. 51",170,"A Conscienciologia é desenvolvida pela menor microminoria — condição dos voluntários das verdades relativas de ponta."),
 "negocinho-evolutivo": dac("Autenfrentamentologia",245,"Jamais adianta querer fazer *negocinho evolutivo* ou pechinchar com as autorresponsabilidades perante o enfrentamento pessoal inevitável das realidades."),
 "obviedade-evolutiva": lo("Obviedade",1379,"A primeira **Ciência Teática** é a evitação da ignorância; a obviedade pode bater no nariz da pessoa e ela nada percebe."),
 "periplo-evolutivo": lo("Semperaprendente",1804,"O périplo evolutivo do semperaprendente é a ação de sair do colo do *evoluciólogo* e ir para os braços do **Ser Serenão.**"),
 "potencializacao-evolutiva": src("Manual da Dupla Evolutiva","dupla","cap. 3",19,"A vivência da dupla evolutiva é o gueixismo mútuo em prol da potencialização da tares e da policarmalidade."),
 "pre-serenao": src("Homo sapiens pacificus","hsp","cap. 357",926,"Quem demora mais: o animal subumano a se tornar pré-serenão, ou o pré-serenão a se tornar Serenão?"),
 "principio-da-empatia-evolutiva": lo("Descrenciologia",605,"A **empatia cognitiva**, assentada ao princípio da descrença, mantém os vínculos conscienciais na CCCI."),
 "priorologia": lo("Priorologia",1629,"A falta de **priorização evolutiva** é uma das reações mais lastimáveis da conscin na vida intrafísica, em geral a sua maior falha."),
 "reagrupamento-evolutivo": lo("Reagrupamento",1696,"O **reagrupamento evolutivo** das consciências lúcidas tem fases distintas — a primeira, a mais difícil, em que muitas personalidades ficam sonolentas pelo caminho."),
 "ruptura-do-equilibrio": dac("Intermissiologia",832,"O equilíbrio intraconsciencial do intermissivista promove a ruptura pessoal com a rotina patológica da Socin, nos empreendedorismos das reciclagens."),
 "teleguiado-autocritico": src("Homo sapiens reurbanisatus","hsr","cap. 65",198,"Teleguiado Autocrítico (Homo sapiens teleguiatus) corresponde a cerca de 65% do Serenão na escala da semiconsciexialidade."),
 "transito-consciencial": lo("Trânsito",1955,"Não se apegue às **coisas da Terra**, você está aqui apenas em trânsito."),
 "simploriedade": lo("Erudiciologia",747,"A Erudiciologia combate, ao mesmo tempo, a ignorância, a inocência, a ingenuidade, a simploriedade e a vulgaridade da conscin."),
}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "abertismo-consciencial": R("abertura omnilateral da autopensenidade","[[interassistencialidade]] · [[continuismo-consciencial]]"),
 "aceleracao-da-historia-pessoal": R("intensificação multidimensional da evolução","[[autevolucao]] · [[know-how-evolutivo]]"),
 "agente-desencadeador": R("quem dinamiza a evolução do assistível","[[evoluciologo]] · [[catalisador]]"),
 "andaime-consciencial": R("muleta já dispensável à evolução","[[hibernante]] · [[autossuficiencia-evolutiva]]"),
 "antissubumanidade": R("posicionar-se contra a subumanidade","[[evolucao-agonistica]] · [[megatolice]]"),
 "aparecimento-dos-evoluciologos": R("hipótese do surgimento público dos evoluciólogos","[[evoluciologo]] · [[pre-serenao]]"),
 "articulador": R("quem articula a evolução grupal","[[evoluciologo]] · [[reagrupamento-evolutivo]]"),
 "atrator": R("realidade com poder de atração evolutiva","[[catalisador]] · [[elo]]"),
 "autevolucao": R("deslocamento gradual e progressivo do ser","[[evolucao-agonistica]] · [[autopromocao-evolutiva]] · [[inteligencia-evolutiva]]"),
 "autodecisor": R("conscin de livre-arbítrio autoconsciente amplo","[[autossuficiencia-evolutiva]] · [[escala-das-prioridades-evolutivas]]"),
 "autopotencializacao": R("fortalecer a si mesma","[[autopromocao-evolutiva]] · [[potencializacao-evolutiva]]"),
 "autopromocao-evolutiva": R("conquista de novo grau pela própria vontade","[[autopotencializacao]] · [[heteropromocao-evolutiva]] · [[autevolucao]]"),
 "autossuficiencia-evolutiva": R("autoconfiança teática conquistada","[[autodecisor]] · [[know-how-evolutivo]]"),
 "catalisador": R("realidade que gera transformação evolutiva","[[agente-desencadeador]] · [[atrator]]"),
 "ciclo-evolutivo-pessoal": R("sequência da sucessão multiexistencial","[[periplo-evolutivo]] · [[transito-consciencial]]"),
 "colheita-intermissiva": R("frutos colhidos no período intermissivo","[[colheita-intrafisica]] · [[andaime-consciencial]]"),
 "colheita-intrafisica": R("desova dos frutos na execução da proéxis","[[colheita-intermissiva]] · [[gestacao-evolutiva]]"),
 "compassageiro-evolutivo": R("consciência que viaja junto na evolução","[[elo]] · [[reagrupamento-evolutivo]]"),
 "condicao-conscienciologica": R("conquista evolutiva alcançada","[[faixa-conscienciologica]] · [[know-how-evolutivo]]"),
 "consciencia-podalica": R("conscin que prioriza os pés no soma","[[megatolice]] · [[subconsciencia-humana]]"),
 "consciex-livre": R("consciex liberta do psicossoma (CL)","[[epiconscienciologia]] · [[periplo-evolutivo]]"),
 "conscin-trator": R("locomotiva social dinâmica","[[articulador]] · [[agente-desencadeador]]"),
 "continuismo-consciencial": R("inteireza sem brechas (trafor)","[[abertismo-consciencial]] · [[trafor-trafar]]"),
 "criacao-do-sucessor": R("formar quem dará continuidade","[[evoluciologo]] · [[heteropromocao-evolutiva]]"),
 "crise-pessoal": R("momento de incertezas e riscos","[[ruptura-do-equilibrio]] · [[gargalo-evolutivo]]"),
 "defasagem-evolutiva": R("falta de sintonia do nível evolutivo","[[equivalencia-evolutiva]] · [[crise-pessoal]]"),
 "descensao-cosmoetica": R("descida paradoxal a serviço da assistência","[[megaparadoxo-evolutivo]] · [[interassistencialidade]]"),
 "devir": R("fluxo permanente, lei geral do Cosmos","[[transito-consciencial]] · [[ponto-transitorio]]"),
 "diferencial-da-conscienciologia": R("característica magna que a distingue","[[revolucao-conscienciologica]] · [[paradigma-consciencial]]" if False else "[[revolucao-conscienciologica]]"),
 "eficacia-evolutiva": R("imprimir eficiência teática à evolução","[[know-how-evolutivo]] · [[marca-de-excelencia]]"),
 "elo": R("relação entre consciências na corrente evolutiva","[[compassageiro-evolutivo]] · [[reagrupamento-evolutivo]]"),
 "ensino": R("transferência de conhecimento correto","[[criacao-do-sucessor]] · [[evoluciologo]]"),
 "epicon-lucido": R("epicentro consciencial-chave","[[teleguiado-autocritico]] · [[semiconsciex]]"),
 "epiconscienciologia": R("ciência da CL e da Serenologia","[[consciex-livre]] · [[holomaturologia]]"),
 "equivalencia-evolutiva": R("igualdade lógica entre níveis evolutivos","[[defasagem-evolutiva]] · [[megaparadoxo-evolutivo]]"),
 "escala-da-consciencia-continua": R("7 estágios de lucidez contínua","[[escala-das-prioridades-evolutivas]] · [[continuismo-consciencial]]"),
 "escala-das-prioridades-evolutivas": R("sequência das prioridades evolutivas","[[priorologia]] · [[planilha-evolutiva]]"),
 "evolucao-agonistica": R("desenvolvimento desde o nível subumano","[[autevolucao]] · [[periplo-evolutivo]]"),
 "evoluciologo": R("condutor/magistrado evolutivo","[[agente-desencadeador]] · [[parassemiologia-do-evoluciologo]] · [[aparecimento-dos-evoluciologos]]"),
 "extrapolacionismo": R("antecipações evolutivas esporádicas","[[know-how-evolutivo]] · [[continuismo-consciencial]]"),
 "faixa-conscienciologica": R("nível/período de manifestação evolutiva","[[condicao-conscienciologica]] · [[escala-da-consciencia-continua]]"),
 "gargalo-evolutivo": R("realização crucial a enfrentar","[[crise-pessoal]] · [[ruptura-do-equilibrio]]"),
 "gestacao-evolutiva": R("produção consciencial progressiva","[[colheita-intrafisica]] · [[autevolucao]]"),
 "hermeneutica-da-evoluciologia": R("interpretação racional da evolução","[[diferencial-da-conscienciologia]] · [[teoria-do-contraponto-interdimensional]]"),
 "heteropromocao-evolutiva": R("promoção externa à conscin","[[autopromocao-evolutiva]] · [[criacao-do-sucessor]]"),
 "hibernante": R("princípio consciencial em qualquer estágio","[[andaime-consciencial]] · [[subconsciencia-humana]]"),
 "hipotese-do-esgotamento-eletronotico": R("suposição do fim da Eletronótica","[[revolucao-conscienciologica]] · [[hipotese-evolutiva]]"),
 "hipotese-evolutiva": R("concepção que esclarece os meandros da evolução","[[hipotese-do-esgotamento-eletronotico]] · [[teoria-do-contraponto-interdimensional]]"),
 "holomaturologia": R("subcampo da Evoluciologia (holomaturidade)","[[epiconscienciologia]] · [[maximologia-evolutiva]]"),
 "informacao-pro-evolutiva": R("conteúdo ideativo prioritário","[[ensino]] · [[know-how-evolutivo]]"),
 "inocencia": R("ausência de mal, por vezes = ignorância","[[simploriedade]] · [[subconsciencia-humana]]"),
 "know-how-evolutivo": R("competência técnica da evolução (IE)","[[inteligencia-evolutiva]] · [[eficacia-evolutiva]] · [[autevolucao]]"),
 "liberologia": R("ciência da liberdade evolutiva","[[descensao-cosmoetica]] · [[consciex-livre]]"),
 "marca-de-excelencia": R("impressão positiva de uma realização","[[eficacia-evolutiva]] · [[know-how-evolutivo]]"),
 "maternacao": R("cuidados de maternar a evolução","[[criacao-do-sucessor]] · [[gestacao-evolutiva]]"),
 "maxiconvergencia-incessante": R("convergir sem cessar para a evolução","[[continuismo-consciencial]] · [[maximizacao]]"),
 "maxidissidente-coadjutor": R("dissidente lúcido à frente do grupo","[[revolucao-conscienciologica]] · [[universalismo]]"),
 "maximizacao": R("elevar ao máximo o rendimento evolutivo","[[maxiconvergencia-incessante]] · [[potencializacao-evolutiva]]"),
 "maximologia-evolutiva": R("condição avançada de cosmovisão evolutiva","[[holomaturologia]] · [[escala-da-consciencia-continua]]"),
 "megamanipulabilidade": R("manipular com intenção cosmoética ampla","[[interassistencialidade]] · [[megaparadoxo-evolutivo]]"),
 "megaparadoxo-evolutivo": R("a mais livre é a mais submissa à Cosmoética","[[descensao-cosmoetica]] · [[equivalencia-evolutiva]]"),
 "megatolice": R("ato máximo de ignorância","[[antissubumanidade]] · [[consciencia-podalica]]"),
 "microminoria-evolutiva": R("minoria da minoria da Humanidade","[[maxidissidente-coadjutor]] · [[consciex-livre]]"),
 "moldura": R("o adorno que substitui o conteúdo","[[megatolice]] · [[negocinho-evolutivo]]"),
 "negocinho-evolutivo": R("pechinchar com as autorresponsabilidades","[[megatolice]] · [[tacon]]"),
 "obviedade-evolutiva": R("avaliação conscienciométrica simples","[[megatolice]] · [[know-how-evolutivo]]"),
 "parassemiologia-do-evoluciologo": R("exame profundo feito pelo evoluciólogo","[[evoluciologo]] · [[conscienciometria]]"),
 "periplo-evolutivo": R("viagem do ser mínimo ao Serenão","[[evolucao-agonistica]] · [[ciclo-evolutivo-pessoal]]"),
 "personalidade-singular": R("caráter cosmoético e evolutivo único","[[marca-de-excelencia]] · [[macrossoma]]" if False else "[[marca-de-excelencia]]"),
 "planilha-evolutiva": R("programa básico da autovivência evolutiva","[[escala-das-prioridades-evolutivas]] · [[priorologia]]"),
 "policonsultoria": R("dar/receber pareceres experientes","[[evoluciologo]] · [[know-how-evolutivo]]"),
 "ponto-transitorio": R("realidade evolutiva sempre dinâmica","[[transito-consciencial]] · [[devir]]"),
 "potencializacao-evolutiva": R("dinamizar teaticamente as conquistas","[[autopotencializacao]] · [[maximizacao]]"),
 "pre-serenao": R("estágio anterior ao Serenão","[[desperto]] · [[periplo-evolutivo]] · [[teleguiado-autocritico]]"),
 "primeiro-tempo-evolutivo": R("autovivência inicial da proéxis","[[segundo-tempo-evolutivo]] · [[escala-das-prioridades-evolutivas]]"),
 "principio-da-empatia-evolutiva": R("empatia derivada de trafores e trafares","[[trafor-trafar]] · [[interassistencialidade]]"),
 "priorologia": R("ciência dos primados das prioridades","[[escala-das-prioridades-evolutivas]] · [[planilha-evolutiva]]"),
 "propulsor-da-vontade": R("agente que impulsiona a vontade","[[autopromocao-evolutiva]] · [[autodecisor]]"),
 "radicalidade-evolutiva": R("posição racional desde a raiz","[[continuismo-consciencial]] · [[know-how-evolutivo]]"),
 "reagrupamento-evolutivo": R("mobilização grupal interassistencial","[[compassageiro-evolutivo]] · [[elo]] · [[articulador]]"),
 "revolucao-conscienciologica": R("transformação/reeducação evolutiva","[[diferencial-da-conscienciologia]] · [[maxidissidente-coadjutor]]"),
 "ruptura-do-equilibrio": R("ação que rompe o equilíbrio rotineiro","[[crise-pessoal]] · [[gargalo-evolutivo]]"),
 "segundo-tempo-evolutivo": R("autovivência da grandeza da maxiproéxis","[[primeiro-tempo-evolutivo]] · [[escala-da-consciencia-continua]]"),
 "ser-hoje": R("a condição realista do aqui-e-agora evolutivo","[[transito-consciencial]] · [[ponto-transitorio]]"),
 "simploriedade": R("comportamento simplório e ingênuo","[[inocencia]] · [[megatolice]]"),
 "sinalizador-evolutivo": R("realidade que sinaliza a evolução","[[atrator]] · [[informacao-pro-evolutiva]]"),
 "subconsciencia-humana": R("conscin abaixo da média evolutiva","[[hibernante]] · [[consciencia-podalica]]"),
 "teleguiado-autocritico": R("conscin autocrítica orientada por consciexes","[[epicon-lucido]] · [[semiconsciex]] · [[pre-serenao]]"),
 "teoria-do-contraponto-interdimensional": R("evolução via contraponto entre dimensões","[[hermeneutica-da-evoluciologia]] · [[hipotese-evolutiva]]"),
 "trafalismo": R("estudo do traço faltante (trafal)","[[trafor-trafar]] · [[principio-da-empatia-evolutiva]]"),
 "transito-consciencial": R("a consciência sempre de passagem","[[ponto-transitorio]] · [[devir]] · [[ser-hoje]]"),
 "vida-centrifuga": R("existência de doações altruístas","[[descensao-cosmoetica]] · [[interassistencialidade]]"),
 "viveiro-evolutivo": R("base intrafísica otimizada para evoluir","[[reagrupamento-evolutivo]] · [[gestacao-evolutiva]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
