# -*- coding: utf-8 -*-
ESP = "Parapatologia"
A = "[[autassedio]]"
def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "aberracao-antifisiologica": dac("Homossexualismologia",772,"A frustração máxima no homossexualismo está na autovivência insolúvel gerada pela própria Antifisiologia ou Antinatureza."),
 "achismo": lo("Achismo",53,"*Achismo: autopensata instintiva.* Quem acha que ninguém presta confessa a própria imprestabilidade evolutiva."),
 "acidia": src("Homo sapiens pacificus","hsp","cap. 1",578,"A *acídia* é o enfraquecimento da vontade levando a pessoa à inércia, à tibieza e à preguiça com abatimento do soma e da consciência."),
 "acriticismo": src("Homo sapiens pacificus","hsp","cap. 2",579,"O *acriticismo* é a postura sem avaliação, exame ou auto e heterocrítica sobre os fatos, sem base em juízo de valor e senso crítico."),
 "agenda-vazia": lo("Agenda",69,"*Agenda: síntese existencial.* — Quer ajudar os amparadores? Melhore a agenda pessoal da tenepes."),
 "alcoolismo": lo("Alcoolismo",77,"*Alcoolismo: autolavagem supercerebral.*"),
 "amoralidade": lo("Amoralidade",95,"*Amoralidade: autotransviamento máximo.* A amoralidade é a legenda da Baratrosfera."),
 "ansiedade-omissiva": lo("Ansiedade",108,"*Ansiedade é prematuridade.* A ansiedade é a primeira manifestação de desequilíbrio mental."),
 "apriorismose": lo("Apriorismose",132,"*Apriorismose: opiniões petrificadas. Apriorismose: autopensene preconceituoso.*"),
 "autassedio": lo("Autassédio",182,"*Autassédio: autengano consentido.* Autassédio é antissabedoria crassa."),
 "autocorrupcao": lo("Autocorrupção",209,"A autocorrupção e o autassédio começam pela pessoa escutando a própria mentira; autovício, megatrafar e autassédio são autocorrupção."),
 "autodesorganizacao": lo("Autodesorganização",220,"A autodesorganização é o atestado da megaignorância; na vida das consciências há mais autodesorganização do que inteligência."),
 "autovitimizacao": lo("Autoculpa",212,"*Autoculpa gera autovitimização.* (E: *Raiva é autovitimização.*)"),
 "buraco-negro-consciencial": src("Homo sapiens pacificus","hsp","cap. 363",945,"Metáfora do buraco negro consciencial — fissura anticosmoética/megatrafar da consciência assistível, campo de trabalho dos amparadores."),
 "cabotinismo": lo("Cabotinismo",366,"*Cabotinismo: autodeificação irracional.* A pessoa exemplarista, quando malinterpretada, pode ser chamada de cabotina."),
 "cinismo": lo("Cinismo",412,"O **cinismo** trava a interassistencialidade; o cinismo, a malícia e a esperteza andam juntos."),
 "comorbidade": lo("Comorbidade",440,"Conviver bem com a **comorbidade pessoal** é manter o equilíbrio dentro do desequilíbrio."),
 "complacencia-religiosa": lo("Complacência",447,"No caminho da evolução, a força da **complacência** é superior à força da violência."),
 "consciencia-retardataria": lo("Atraso",175,"Nas minitertúlias há a conscin retardatária cotidiana e a eventual; o atraso eventual é compreensível."),
 "conscin-mal-resolvida": src("Homo sapiens reurbanisatus","hsr","cap. 185",454,"A maioria das consréus ressomadas é mal-resolvida quanto aos cons, vítima dos criptocons."),
 "conscin-multivola": lo("Multívola",1332,"A condição da conscin multívola (insatisfazível) predomina no sexo feminino, especialmente nas pessoas hiperativas."),
 "consreu-estelar": lo("Consréu",506,"*Consréu: analfabeta cósmica. Consréu: caráter pernicioso.*"),
 "decidofobia": src("Homo sapiens pacificus","hsp","cap. 31",598,"A *decidofobia* é a condição patológica da pessoa indecisa, com medo de decidir ou tomar posição ante as injunções críticas da vida (neologismo da Psicossomática)."),
 "desafeicao": lo("Desafeição",593,"*Incompreensão gera desafeição.* Não existe desafeição sem incompreensão."),
 "desequilibrio-mental": lo("Desequilíbrio",608,"Não existem loucos espertos; a vida desequilibrada é o caos."),
 "dificultador-evolutivo": lo("Apriorismo",132,"O maior dificultador para a consciência receber assistência é o **autapriorismo amaurótico.**"),
 "distorcao-cognitiva": src("Homo sapiens pacificus","hsp","cap. 329",880,"O *fator de distorção autoconsciencial* compõe a condição de autassédio (intra) ou heterassédio (inter) na conscin desestabilizada."),
 "doutrinacao": src("Homo sapiens pacificus","hsp","cap. 40",603,"A *doutrinação* é o ato de doutrinar, impingindo ou inculcando algum tipo de conhecimento dogmático."),
 "drama-de-consciencia": lo("Drama",670,"O drama da evolução do princípio consciencial tem 3 atos: ressomar, reviver e dessomar, repetidos pelos milênios."),
 "energima": src("Homo sapiens pacificus","hsp","cap. 283",787,"Após o afastamento dos amparadores, nasce a possessão interconsciencial ou energima — manifestação primária do belicismo."),
 "falaciologia": lo("Falaciologia",845,"No universo da **Falaciologia** entram os pensenes conscientes e inconscientes que estruturam as demagogices e os tolicionários."),
 "fascinio-pelo-grotesco": lo("Grotesco",935,"O **grotesco** torna-se *ridículo* por si mesmo."),
 "felicidade-patologica": lo("Felicidade",864,"Quem se sente inteiramente feliz no holopensene da Socin Patológica ainda vive carente de maior inteligência primária."),
 "forca-do-atraso": lo("Atraso",175,"A **conscin atrasilda** é, inevitavelmente, desorganizada."),
 "guia-desorientador": lo("Guia",940,"O **guia extrafísico amaurótico** é uma bússola sem ponteiro, daí os desatinos dos dogmas das seitas e religiões."),
 "gurulatria": src("Homo sapiens pacificus","hsp","cap. 361",941,"O *Homo sapiens serenissimus* torna impraticáveis a gurulatria, o misticismo, a doutrinação e o salvacionismo."),
 "heterassedio": src("Homo sapiens pacificus","hsp","cap. 47",607,"Os vocábulos *heterassédio* e *heterassediopata* são neologismos técnicos da Parapatologia; o mal funciona mesmo com a vítima ignorando-o."),
 "hibernacao-cultural": lo("Hibernação",956,"A vida fetal e a comatose são **estados hibernais** do princípio consciencial."),
 "hipocondria": src("700 Experimentos da Conscienciologia","700exp","cap. 369",433,"A hipocondria é neurose branda de origem emocional, adstrita ao sexossoma/subcérebro abdominal, reflexo do psicossoma."),
 "hipocrisia-politica": lo("Hipocrisia",960,"É muito difícil identificar onde a **hipocrisia** mais atua: se na Política ou na Religião."),
 "hipotensao": src("Homo sapiens pacificus","hsp","cap. 50",609,"A *hipotensão* é a pressão inferior à normal — perda da força vital, bradicardia, sensibilidade ao frio, desânimo."),
 "idolatria": lo("Idolatria",1000,"*Idolatria: excrescência descartável.* A Mitologia está na gênese de toda idolatria."),
 "ignorantismo": src("Homo sapiens pacificus","hsp","cap. 6",31,"O Absolutismo é irmão gêmeo do Ignorantismo (a doutrina de que a instrução é perniciosa)."),
 "ilogicidade": lo("Ilogicidade",1009,"*Ilogicidade: força superfraca.*"),
 "inautenticidade": src("700 Experimentos da Conscienciologia","700exp","cap. 470",534,"A hipocrisia comum nasce da inautenticidade; a insinceridade como inautenticidade pode ser mascarada sem esforço."),
 "incivilidade": src("Homo sapiens pacificus","hsp","cap. 54",611,"A *incivilidade* é a falta de civilidade ou da educação da cidadania e consciência comunitária."),
 "interiorose": src("Homo sapiens pacificus","hsp","cap. 60",615,"*Interiorose, antiinteriorose* e *interiorota* são neologismos técnicos da Intrafisicologia (o superradicado ao interior)."),
 "intermissivista-inadaptado": dac("Adaptaciologia",90,"O intermissivista inadaptado é a conscin que sabe tudo e não cumpre nada — ainda não se adaptou às dádivas."),
 "irracionalidade-religiosa": lo("Irracionalidade",1116,"*Irracionalidade: ignorância mantida.* A maior irracionalidade é pretender que os efeitos precedam as causas."),
 "irreflexao-pre-verbal": lo("Irreflexão",1116,"*Toda irreflexão enfraquece.* À pessoa irrefletida, até o pensamento mais obscuro pode parecer profundo."),
 "irresponsabilidade": src("Homo sapiens pacificus","hsp","cap. 61",615,"A *irresponsabilidade* é a condição da pessoa não cumpridora dos próprios deveres ou obrigações."),
 "iscagem-interconsciencial": src("Homo sapiens pacificus","hsp","cap. 62",616,"A *iscagem interconsciencial* (neologismo da Energossomática) é a conscin atuando como isca energética; há a iscagem inconsciente e as afinidades patológicas."),
 "ludopatia": src("Homo sapiens pacificus","hsp","cap. 63",616,"A *ludopatia* é o vício de praticar jogos de azar (baralhos, dados, roleta, bingo) de modo intenso e prolongado."),
 "maniologia": lo("Maniologia",1215,"A Maniologia estuda os hábitos extravagantes; corta-se os caprichos de olho no megafoco para evitar Maniologia e correlatas."),
 "megapatologia-intraconsciencial": lo("Megapatologia",1260,"Toda **guerra** é megapatologia contra a vida humana."),
 "megatolice-indefensavel": src("Homo sapiens pacificus","hsp","cap. 209",550,"A *megatolice indefensável* é o ato impensado de efeitos negativos, imediatos ou mediatos, para a conscin tola e seus seguidores incautos."),
 "megatrafar": lo("Megatrafar",1269,"*Megatrafar: autopropensão viciosa.* É megatrafar procurar justificar os autotrafares."),
 "megatrafar-antimaxiproexis": lo("Megatrafar",1269,"*Megatrafar: autopropensão viciosa* — o traço-fardo mais atuante contra a maxiproéxis."),
 "megatrafar-explicito": lo("Megatrafar",1269,"*Megatrafar: autopropensão viciosa* — manifestação aberta e pública do megadefeito."),
 "melin": lo("Melin",1274,"A **melin** mela a vida; muitas crises de autodepressão se devem à melin."),
 "neofobia": src("Homo sapiens reurbanisatus","hsr","cap. 10",53,"A inépcia e a neofobia andam de mãos dadas (tecnofobia)."),
 "paracriminologia": src("Homo sapiens pacificus","hsp","cap. 16",71,"A *Paracriminologia* estuda os atos criminosos das consciexes sobre conscins e consciexes, incluindo megassédios e megapossessões — temas da Consciencioterapia."),
 "personalismo": src("Homo sapiens pacificus","hsp","cap. 72",621,"O *personalismo* é referir todas as coisas a si mesmo, fazendo predominar os interesses pessoais sobre os demais."),
 "prejuizo-sorrateiro": lo("Megassediador",1265,"O *megassediador* é sorrateiro: a víbora morde sem ruído."),
 "prurido-consciencial": lo("Prurido",1662,"*Prurido: cafubira aristocrata.* O prurido é que incomoda mais certas pessoas superficiais."),
 "psicopatia": lo("Psicopatia",1669,"A pior **psicopatia** é o ato de a conscin pensenizar erradamente; quem tem psicopatia não admite heterocríticas."),
 "racismo": lo("Racismo",1689,"O **racismo** jamais deixa de ser uma questão genuinamente animal; é pura ignorância."),
 "retardamento-mental-coletivo": src("Homo sapiens pacificus","hsp","cap. 171",472,"A psicose é distúrbio mental grave com desagregação da personalidade, deformação da realidade e conduta regressiva — base do retardamento coletivo."),
 "riscomania": lo("Riscomania",1771,"*A riscomania mata. A autorganização vivifica.*"),
 "sarcasmo": src("Homo sapiens pacificus","hsp","cap. 82",627,"O *sarcasmo* é o ato gerador da ironia cáustica ou zombaria ofensiva."),
 "satisfacao-malevola": lo("Schadenfreude",1796,"A satisfação malévola (*Schadenfreude*) mais sutil é a da conscin que se sente bem com o vício de outrem."),
 "silencio-omissivo": dac("Silenciologia",1353,"Há 12 categorias de silêncios do Homo sapiens autorreflexor; o silêncio omissivo é o calar-se obtuso que prejudica."),
 "sindrome-da-abstinencia-da-baratrosfera": lo("Paranostalgias",1471,"A *Síndrome da Abstinência da Baratrosfera* (SAB) é a patoparanostalgia."),
 "sindrome-da-autossantificacao": src("Homo sapiens pacificus","hsp","cap. 230",652,"Há 61 síndromes — variáveis da Conscienciologia — incluídas nos 100 grupos nosográficos da Parapatologia."),
 "sindrome-da-mediocrizacao": src("700 Experimentos da Conscienciologia","700exp","cap. 386",450,"A síndrome da mediocrização consciencial decorre de ausências de oportunidades, autocorrupções e ceticismo; é doença autestagnante da Parapatologia do holossoma."),
 "subadultidade": src("Homo sapiens pacificus","hsp","cap. 85",629,"A *subadultidade* (neologismo da Paracronologia) é o adulto biológico ainda adolescente mental ou psiquicamente."),
 "subcerebralidade": src("Homo sapiens pacificus","hsp","cap. 86",630,"A *subcerebralidade* (neologismo da Mentalsomática) é o indivíduo com reações predominantemente subcerebrais ou irracionais."),
 "sujismundismo": src("Homo sapiens pacificus","hsp","cap. 88",630,"O *sujismundismo* é o descaso quanto ao asseio pessoal e ambiental (do personagem Sujismundo, 1971)."),
 "tedio": lo("Tédio",1903,"*Tédio: enfermidade cognitiva.* Quem nivela os atos por cima jamais se torna vítima do tédio."),
 "tirania": lo("Tirania",1934,"*Tirania: tragédia anunciada. Tirania representa caos.*"),
 "toxicomania": lo("Toxicomania",1940,"No universo degradado das drogas, as dívidas são pagas com a própria vida humana."),
 "traumatismo": src("Homo sapiens pacificus","hsp","cap. 94",634,"O *traumatismo* é o conjunto de lesões provocadas por agente externo, ferindo física e psiquicamente o indivíduo."),
 "travao": lo("Conscienciografia",486,"O maior **travão** da escrita útil é o autassédio."),
 "triade-da-erronia": lo("Autorrespeito",291,"Quando falta o autorrespeito cosmoético, a tríade autocorrupção-autassédio-autoinsegurança domina a personalidade."),
 "truculencia": src("Homo sapiens pacificus","hsp","cap. 95",635,"A *truculência* é a reação da pessoa brutal, grosseira, sem finura, atuando através de atos de violência."),
 "verborragia": src("Homo sapiens pacificus","hsp","cap. 97",636,"A *verborragia* é o uso de quantidade excessiva de palavras para dizer coisas de conteúdo pobre (pessoa tagarela)."),
 "xenofobia": lo("Xenofobia",2047,"A **xenofobia** é uma reação primária da pessoa primatológica, preconceituosa (Homo obtusus), sem o Código Pessoal de Cosmoética."),
 "socin-viciada": src("Homo sapiens reurbanisatus","hsr","cap. 196",472,"A imaginação viciada e a verborragia são exemplos da Parapatologia da Socin Viciada."),
 "encolhimento-consciencial": src("Manual da Dupla Evolutiva","dupla","cap. 39",161,"O subcérebro abdominal é responsável pelo encolhimento do cérebro natural e pela condição da conscin sexólica das duplas estacionárias."),
 "tabagismo": lo("Tabagismo",1885,"O **tabagismo** é um absurdo, não tem nexo: o número dos tolos é infinito."),
}
CONV = {k:v for k,v in CONV.items() if v}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
B="[[baratrosfera]]"; P="[[patopensene]]"; SUB="[[subcerebro-abdominal]]"; H="[[heterassedio]]"; CT="[[consciencioterapia]]"
REL = {
 "aberracao-antifisiologica": R("conduta contra a fisiologia natural","[[megatrafar]] · "+SUB),
 "achismo": R("teorização sem autovivência","[[acriticismo]] · [[apriorismose]]"),
 "acidia": R("enfraquecimento da vontade (inércia)","[[tedio]] · [[autodesorganizacao]]"),
 "acriticismo": R("postura sem juízo crítico","[[achismo]] · [[apriorismose]]"),
 "agenda-vazia": R("falta de programação útil","[[autodesorganizacao]] · [[indisciplina]]"),
 "alcoolismo": R("dependência química ao álcool","[[toxicomania]] · [[tabagismo]] · "+SUB),
 "amoralidade": R("ausência de moral (legenda da Baratrosfera)",B+" · [[autocorrupcao]]"),
 "ansiedade-omissiva": R("apreensão sem causa por omissão","[[silencio-omissivo]] · [[desequilibrio-mental]]"),
 "anticetico": R("partidário do Anticeticismo","[[doutrinacao]] · [[irracionalidade-religiosa]]"),
 "antidireito": R("o injusto contra a Lei/Ciência","[[parailicitude]] · [[sequenciamento-imoral]]"),
 "antiespecialidade-conscienciologica": R("conscin contra a vivência da especialidade","[[autorregressismo]] · [[fechadismo-consciencial]]"),
 "apriorismose": R("opiniões petrificadas, preconceituosas","[[fechadismo-consciencial]] · [[neofobia]]"),
 "assedin": R("promotor do assédio intrafísico",H+" · [[assedio-bioquimico]]"),
 "assedio-bioquimico": R("perturbação via substâncias no soma","[[alcoolismo]] · [[toxicomania]] · "+SUB),
 "autaniquilamento-do-pesquisador": R("reação patológica do pesquisador","[[autassedio]] · [[megapatologia-intraconsciencial]]"),
 "autassedio": R("automolestação consentida (autengano)","[[heterassedio]] · [[autocorrupcao]] · "+P),
 "autocorrupcao": R("repetir o ato desconfortável injustificável","[[autassedio]] · [[megatrafar]] · [[triade-da-erronia]]"),
 "autodesorganizacao": R("viver desordenado/desestruturado","[[agenda-vazia]] · [[indisciplina]] · [[acidia]]"),
 "autopatia": R("sentimento egoísta doentio","[[personalismo]] · [[possessividade]]"),
 "autoperdoador": R("perdoa os próprios erros sem reciclar","[[autocorrupcao]] · [[superestimacao-pontual]]"),
 "autorregressismo": R("regredir a condição evolutiva","[[interacao-regressiva]] · [[fechadismo-consciencial]]"),
 "autovitimizacao": R("vitimizar-se/depreciar-se","[[melin]] · [[ansiedade-omissiva]]"),
 "basbaquice": R("admiração tola e ingênua","[[idolatria]] · [[gurulatria]]"),
 "buraco-negro-consciencial": R("fissura anticosmoética/megatrafar","[[megatrafar]] · [[parafissura-consciencial]]"),
 "cabotinismo": R("autodeificação irracional","[[personalismo]] · [[megaidiotismo-cultural]]"),
 "canga-tribal": R("trafar de robotização social","[[subcerebralidade]] · "+B),
 "cinismo": R("descaso pela moral e convenções","[[sarcasmo]] · [[hipocrisia-politica]]"),
 "comorbidade": R("coexistência de doenças","[[megapatologia-intraconsciencial]] · [[psicopatia]]"),
 "complacencia-religiosa": R("tolerância dogmática das ideologias","[[doutrinacao]] · [[irracionalidade-religiosa]]"),
 "consciencia-retardataria": R("conscin atrasada nos compromissos","[[forca-do-atraso]] · [[indisciplina]]"),
 "consciencia-titere": R("personalidade débil submissa","[[heterassedio]] · [[consciencia-retardataria]]"),
 "conscin-mal-resolvida": R("vítima de fracasso não resolvido","[[melin]] · [[autovitimizacao]]"),
 "conscin-multivola": R("insatisfazível, hiperativa","[[possessividade]] · [[autopatia]]"),
 "consreu-estelar": R("consréu com liderança ainda viciada",B+" · [[megatrafar]]"),
 "contraponto-heterassediador": R("ocorrências baratrosféricas conjugadas",H+" · "+B),
 "corrente-baratrosferica": R("intoxicação comunicativa baratrosférica",B+" · [[inspiracao-baratrosferica]]"),
 "criatividade-irresponsavel": R("dom criativo sem cosmoética","[[irresponsabilidade]] · [[sequenciamento-imoral]]"),
 "decidofobia": R("medo patológico de decidir","[[ansiedade-omissiva]] · [[desequilibrio-mental]]"),
 "desafeicao": R("perda de afeição (incompreensão)","[[autopatia]] · [[truculencia]]"),
 "desequilibrio-mental": R("desarmonia ativa do microuniverso","[[psicopatia]] · [[megapatologia-intraconsciencial]]"),
 "dificultador-evolutivo": R("o que obstaculiza a evolução","[[forca-do-atraso]] · [[apriorismose]]"),
 "distorcao-cognitiva": R("fator de distorção autoconsciencial","[[autassedio]] · [[raciocinio-falho]]"),
 "disturbio-aleatorio": R("ocorrência perturbadora imprevisível","[[minicontratempo]] · [[distorcao-cognitiva]]"),
 "doutrinacao": R("inculcar conhecimento dogmático","[[gurulatria]] · [[complacencia-religiosa]] · [[irracionalidade-religiosa]]"),
 "drama-de-consciencia": R("autovivência fixada em autoculpa","[[autovitimizacao]] · [[melin]]"),
 "encolhimento-consciencial": R("contração doentia da consciência",SUB+" · [[hibernacao-cultural]]"),
 "energima": R("possessão interconsciencial",H+" · [[paragangue]]"),
 "equivoco": R("erro consciente ou inconsciente","[[raciocinio-falho]] · [[minifalha]]"),
 "falaciologia": R("ciência das falácias/demagogices","[[raciocinio-falho]] · [[achismo]]"),
 "fascinio-pelo-grotesco": R("encanto pelo grotesco","[[basbaquice]] · [[idolatria]]"),
 "fechadismo-consciencial": R("fechamento omnilateral neofóbico","[[neofobia]] · [[apriorismose]] · [[autorregressismo]]"),
 "felicidade-patologica": R("pseudoplenitude na Socin Patológica","[[frivolidade-moral]] · [[omnifrivolizacao]]"),
 "forca-do-atraso": R("fator que trava a evolução","[[dificultador-evolutivo]] · [[consciencia-retardataria]]"),
 "frivolidade-moral": R("futilidade da consciência humana","[[omnifrivolizacao]] · [[felicidade-patologica]]"),
 "guia-desorientador": R("guia amaurótico que desorienta","[[gurulatria]] · [[doutrinacao]]"),
 "gurulatria": R("culto ao líder carismático de seita","[[idolatria]] · [[doutrinacao]] · [[basbaquice]]"),
 "heterassedio": R("submissão ao assédio externo","[[autassedio]] · [[assedin]] · [[energima]]"),
 "hibernacao-cultural": R("retraimento intelectual","[[encolhimento-consciencial]] · [[neofobia]]"),
 "hipocondria": R("foco compulsivo na própria saúde",SUB+" · [[melin]]"),
 "hipocrisia-politica": R("insinceridade sociopata","[[cinismo]] · [[inautenticidade]]"),
 "hipotensao": R("pressão abaixo do normal (perda de força vital)","[[acidia]] · [[traumatismo]]"),
 "idolatria": R("culto a ídolos","[[gurulatria]] · [[basbaquice]] · [[irracionalidade-religiosa]]"),
 "ignorantismo": R("doutrina de que a cultura é perniciosa","[[irracionalidade-religiosa]] · [[megaidiotismo-cultural]]"),
 "ilogicidade": R("desprovido de lógica","[[raciocinio-falho]] · [[irracionalidade-religiosa]]"),
 "impulso-desumano": R("ato instintual sem freio","[[subcerebralidade]] · [[truculencia]]"),
 "inautenticidade": R("falta de genuinidade (gera hipocrisia)","[[hipocrisia-politica]] · [[cinismo]]"),
 "incivilidade": R("falta de civilidade/educação cidadã","[[truculencia]] · [[sarcasmo]]"),
 "indisciplina": R("falta de firmeza ante normas","[[autodesorganizacao]] · [[agenda-vazia]]"),
 "inspiracao-baratrosferica": R("ideia doentia inspirada na baratrosfera",B+" · [[corrente-baratrosferica]]"),
 "intempestividade": R("inoportunidade do agir","[[irreflexao-pre-verbal]] · [[minicontratempo]]"),
 "interacao-regressiva": R("interação não-evolutiva da vulgar","[[autorregressismo]] · [[subcerebralidade]]"),
 "interiorose": R("superradicamento ao interior","[[bairrismo]]" if False else "[[hibernacao-cultural]] · [[fechadismo-consciencial]]"),
 "intermissivista-inadaptado": R("ex-aluno do CI que não cumpre","[[apriorismose]] · [[autassedio]]"),
 "invalidez-parapsiquica": R("incapacidade parapsíquica","[[hibernacao-cultural]] · [[heterassedio]]"),
 "irracionalidade-religiosa": R("posturas irracionais religiosas","[[idolatria]] · [[doutrinacao]] · [[ignorantismo]]"),
 "irreflexao-pre-verbal": R("falar sem pensar antes","[[intempestividade]] · [[verborragia]]"),
 "irresponsabilidade": R("não cumprir deveres/obrigações","[[criatividade-irresponsavel]] · [[indisciplina]]"),
 "iscagem-interconsciencial": R("conscin como isca energética",H+" · [[energima]]"),
 "linguagem-corruptora": R("comunicar ideias anticosmoéticas","[[falaciologia]] · "+P),
 "ludopatia": R("vício em jogos de azar","[[toxicomania]] · [[riscomania]]"),
 "maniologia": R("ciência dos hábitos extravagantes","[[riscomania]] · [[possessividade]]"),
 "megaidiotismo-cultural": R("presunção étnica/racista","[[racismo]] · [[xenofobia]] · [[ignorantismo]]"),
 "megapatologia-intraconsciencial": R("nosografia máxima da consciência","[[megatrafar]] · [[psicopatia]] · "+CT),
 "megatolice-indefensavel": R("ato impensado de efeitos negativos","[[megatrafar]] · [[sustentacao-do-erro]]"),
 "megatrafar": R("o maior traço-fardo (megadefeito)","[[megatrafar-explicito]] · [[megatrafar-antimaxiproexis]] · [[autocorrupcao]]"),
 "megatrafar-antimaxiproexis": R("trafar que sabota a maxiproéxis","[[megatrafar]] · [[megatrafar-explicito]]"),
 "megatrafar-explicito": R("megadefeito aberto e público","[[megatrafar]] · [[megatrafar-antimaxiproexis]]"),
 "melin": R("melancolia intrafísica (autodepressão)","[[autovitimizacao]] · [[drama-de-consciencia]]"),
 "micrassediador-invisivel": R("microrganismo patogênico","[[assedio-bioquimico]] · [[comorbidade]]"),
 "minicontratempo": R("contratempo fortuito desagradável","[[disturbio-aleatorio]] · [[minifalha]]"),
 "minifalha": R("pequena falta/omissão","[[equivoco]] · [[minicontratempo]]"),
 "neofobia": R("repulsa às novidades/progresso","[[fechadismo-consciencial]] · [[apriorismose]] · [[hibernacao-cultural]]"),
 "omnifrivolizacao": R("predomínio da frivolidade na vida","[[frivolidade-moral]] · [[felicidade-patologica]]"),
 "onirismo": R("estado anormal de irrealidade onírica","[[inspiracao-baratrosferica]] · [[distorcao-cognitiva]]"),
 "paracriminologia": R("criminologia extrafísica baratrosférica","[[paragangue]] · "+CT),
 "parafissura-consciencial": R("desordem anticosmoética do microuniverso","[[buraco-negro-consciencial]] · [[megatrafar]]"),
 "paragangue": R("associação de consciexes assediadoras",B+" · [[energima]] · [[paracriminologia]]"),
 "parailicitude": R("manifestação dolosa extrafísica","[[antidireito]] · [[sequenciamento-imoral]]"),
 "personalismo": R("referir tudo a si mesmo","[[autopatia]] · [[possessividade]] · [[cabotinismo]]"),
 "possessividade": R("sentimento exagerado de posse","[[personalismo]] · [[conscin-multivola]]"),
 "prejuizo-sorrateiro": R("dano oculto, não raro fatal","[[micrassediador-invisivel]] · [[megassediador]]" if False else "[[micrassediador-invisivel]] · [[satisfacao-malevola]]"),
 "prurido-consciencial": R("inquietação/desconforto íntimo","[[ansiedade-omissiva]] · [[tedio]]"),
 "psicopatia": R("doença mental (pensenizar errado)","[[desequilibrio-mental]] · [[megapatologia-intraconsciencial]]"),
 "raciocinio-falho": R("pensenização truncada/ilógica","[[ilogicidade]] · [[distorcao-cognitiva]] · [[falaciologia]]"),
 "racismo": R("crença na superioridade de raças","[[xenofobia]] · [[megaidiotismo-cultural]]"),
 "rainha": R("soberana de poder absoluto (figura)","[[tirania]] · [[idolatria]]"),
 "retardamento-mental-coletivo": R("condição sindrômica pandêmica","[[sindrome-da-mediocrizacao]] · [[megaidiotismo-cultural]]"),
 "riscomania": R("expor-se a ameaças (mau hábito)","[[ludopatia]] · [[maniologia]]"),
 "sarcasmo": R("ironia cáustica ofensiva","[[cinismo]] · [[incivilidade]]"),
 "satisfacao-malevola": R("prazer no fracasso alheio (Schadenfreude)","[[prejuizo-sorrateiro]] · [[cinismo]]"),
 "sequenciamento-imoral": R("dar continuidade ao anticosmoético","[[parailicitude]] · [[sustentacao-do-erro]]"),
 "silencio-omissivo": R("calar-se de modo obtuso","[[ansiedade-omissiva]] · [[sustentacao-do-erro]]"),
 "sindrome-da-abstinencia-da-baratrosfera": R("patoparanostalgia da baratrosfera",B+" · [[inspiracao-baratrosferica]]"),
 "sindrome-da-autossantificacao": R("síndrome do autossantificar-se","[[cabotinismo]] · [[superestimacao-pontual]]"),
 "sindrome-da-mediocrizacao": R("doença autestagnante (Parapatologia do holossoma)","[[sindrome-da-subestimacao]] · [[acidia]]"),
 "sindrome-da-subestimacao": R("desvalorização das próprias potencialidades","[[sindrome-da-mediocrizacao]] · [[autovitimizacao]]"),
 "sindrome-de-amiel": R("autossabotagem da produção gráfica","[[sindrome-da-subestimacao]] · [[procrastinacao]]" if False else "[[sindrome-da-subestimacao]] · [[autocorrupcao]]"),
 "socin-viciada": R("Sociedade Intrafísica dominada por vícios",B+" · [[corrente-baratrosferica]]"),
 "solidariedade-maligna": R("cumplicidade na culpa","[[sequenciamento-imoral]] · [[paragangue]]"),
 "subadultidade": R("adulto biológico, adolescente mental","[[subcerebralidade]] · [[irresponsabilidade]]"),
 "subcerebralidade": R("reações predominantemente subcerebrais",SUB+" · [[impulso-desumano]]"),
 "subjugabilidade": R("condição de ser subjugável",H+" · [[consciencia-titere]]"),
 "sucumbencia": R("cair sob o peso de força interna/externa","[[heterassedio]] · [[megapatologia-intraconsciencial]]"),
 "sujismundismo": R("descaso com a higiene","[[autodesorganizacao]] · [[incivilidade]]"),
 "superestimacao-pontual": R("autassédio por superestimar-se","[[autoperdoador]] · [[sindrome-da-autossantificacao]]"),
 "sustentacao-do-erro": R("manter o erro por indiferença","[[megatolice-indefensavel]] · [[sequenciamento-imoral]]"),
 "tabagismo": R("dependência do tabaco","[[toxicomania]] · [[alcoolismo]]"),
 "tedio": R("enfado/cansaço (enfermidade cognitiva)","[[acidia]] · [[prurido-consciencial]]"),
 "tirania": R("poder usurpado e ilegal","[[rainha]] · [[truculencia]]"),
 "toxicomania": R("consumo compulsivo de substâncias","[[alcoolismo]] · [[tabagismo]] · [[ludopatia]]"),
 "trafarao": R("conscin imatura, acrítica, egoica","[[subcerebralidade]] · [[megatrafar]]"),
 "traumatismo": R("lesões por agente externo","[[hipotensao]] · [[micrassediador-invisivel]]"),
 "travao": R("o que trava a manifestação útil","[[autassedio]] · [[forca-do-atraso]]"),
 "triade-da-erronia": R("velhacaria-erronia-absurdidade","[[autocorrupcao]] · [[megatrafar]]"),
 "truculencia": R("brutalidade/violência sem finura","[[impulso-desumano]] · [[incivilidade]] · [[tirania]]"),
 "verborragia": R("excesso de palavras de conteúdo pobre","[[irreflexao-pre-verbal]] · [[linguagem-corruptora]]"),
 "xenofobia": R("aversão ao estranho ao meio","[[racismo]] · [[megaidiotismo-cultural]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
