# -*- coding: utf-8 -*-
ESP = "Intrafisicologia"
A = "[[intrafisicalidade]]"
def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "alcova-blindada": src("200 Teáticas da Conscienciologia","200teat","cap. 5",25,"Na técnica da transferência sexochacral de energias é indispensável o emprego de uma alcova energeticamente blindada."),
 "alcova-contaminada": lo("Sonologia",1861,"Uma **alcova contaminada** prejudica a projetabilidade lúcida — resultado da falta de higiene consciencial."),
 "alienacao": lo("Alienação",81,"*Alienação: semimorte antiproéxis.*"),
 "animal-humano": lo("Princípios",1627,"*Pré-humano: animal instintivo. Humano: animal semirracional. CL: ex-animal ex-irracional.*"),
 "anomia": src("Homo sapiens pacificus","hsp","cap. 286",790,"A *anomia* é o estado de caos ou ruptura característico dos períodos de dissolução das normas, leis e regras sociais."),
 "automovel": lo("Automóvel",250,"**Automóvel:** animal doméstico tecnológico de tração."),
 "autovendagem": lo("Autovendagem",310,"A acomodação à autovendagem consciente a alguma ideologia, sem o princípio da descrença, mantém a autorregressão evolutiva."),
 "autovivencia": lo("Autovivência",312,"*Autovivência: holoteca experiencial.* A prática é a autovivência."),
 "bairrismo": src("Homo sapiens reurbanisatus","hsr","cap. 224",566,"A conscin arraigada ao bairrismo ainda não conseguiu ajustar a bússola consciencial ao universalismo."),
 "biofilia": src("Homo sapiens reurbanisatus","hsr","cap. 15",125,"A expressão *biofilia equilibrada* é neologismo técnico da Intrafisicologia (amor à vida, instinto de preservação)."),
 "biofilia-monopolizadora": src("200 Teáticas da Conscienciologia","200teat","cap. 29",49,"Pela intrafisicologia, 75% do espaço e do tempo conscienciais devem ser dedicados à vida humana; em detrimento da conscienciofilia, a biofilia torna-se monopolizadora e negativa."),
 "conscin-eletronotica": lo("Eletronótica",699,"Quem vivencia as **retrocognições** desvaloriza a importância da Ciência Convencional, apenas eletronótica."),
 "conscin-large": lo("Large",1148,"A **conscin *large*** é a pessoa doadora, assistencial, de maior amplitude fraterna."),
 "condominio-cognopolitano": lo("Condomínio",469,"O *Estado Mundial* transformará a Terra num **Condomínio Planetário.**"),
 "culturologia": dac("Culturologia",554,"Na vida humana há 2 realidades básicas: a Culturologia (costumes das tradições étnicas) e a Conscienciologia."),
 "efeito-macho-femea": lo("Imperfeições",1019,"*Homem: fêmea imperfeita. Mulher: macho imperfeito.*"),
 "esbanjamento-consciencial": src("Projeciologia","proj","cap. 144",323,"Há a frustração do esbanjamento da energia consciencial (parapsicopatologia do mentalsoma)."),
 "exigencia-da-vida-humana": src("200 Teáticas da Conscienciologia","200teat","cap. 140",160,"Pela comunicologia, toda exigência de perfeccionismo gera conflito na vivência sadia da comunicabilidade humana."),
 "exilado-na-propria-patria": lo("Pátria",1510,"A pátria da megafraternidade é o **Cosmos**; quem insiste em pátria e patriotismo são os recrutadores para a guerra."),
 "falsidade-objetal": dac("Transparenciologia",1413,"Na Terra, capital da falsidade objetal, não se pode esperar que tudo tenha transparência; ainda vivemos, em muitas circunstâncias, na Mentirolândia."),
 "fartura": src("Manual da Tenepes","tnp","cap. 32",77,"A *teoria da fartura de energia consciencial* — comprovável na própria vida — é proposta inédita da Conscienciologia."),
 "fatologia": lo("Fatologia",858,"*Os fatos impõem.* A complexidade dos fatos decorre da influência do maior número de consciências intra e extrafísicas."),
 "forca-presencial": lo("Holosfera",977,"A força presencial está assentada na **holosfera** da conscin."),
 "funcionalidade": lo("Funcionalidade",893,"*Respeitemos a funcionalidade.* A abordagem permite a autabsorção teórica; a prática do absorvido permite a autovivência evolutiva — funcionalidade da evolução."),
 "ilha-de-consciencialidade": lo("Ilha",1007,"O **ser desperto** é uma ilha inundável no oceano das experiências humanas."),
 "impossibilidade-natural": lo("Impossibilidade",1022,"*Impossibilidade é inexperiência.* A aparente impossibilidade deixa de existir ao buscarmos vivenciá-la."),
 "industria-paralela": src("Homo sapiens reurbanisatus","hsr","cap. 5",40,"A indústria paralela gera a anticosmoética, a contravenção e a marginalidade, solapando setores da economia formal."),
 "jubileu-evolutivo": dac("Autoparajubilaciologia",379,"Todo autoparajubileu multidimensional expressa ao menos 1 trio de jubilações convergentes (acadêmico, etc.)."),
 "longevidade-produtiva": lo("Longevidade",1189,"Sem a infância e a adolescência equilibradas, não há **longevidade** produtiva; longevidade é megarresponsabilidade."),
 "posicionamento-pre-dessomatico": lo("Autocomatose",200,"*Autocomatose: onirismo pré-dessomático.*"),
 "poupanca-existencial": lo("Poupança",1595,"A **poupança** é ativa: tesouro escondido não é poupança; poupança é o maior ganho."),
 "relatividade": lo("Relatividade",1721,"Somente a **autolucidez** da consciência mantém a relatividade das coisas em nível sadio."),
 "residencia-proexogenica": lo("Lar",1147,"A **casa proexogênica** é a casa-máquina que hospeda o corpo humano."),
 "rotina-util": lo("Rotina",1776,"A **rotina útil** suaviza os autesforços evolutivos; é a batopensenidade intencional, cosmoética."),
 "taxologia-dos-analogismos": src("Homo sapiens reurbanisatus","hsr","cap. 160",402,"Tabela dos percentuais dos analogismos lógicos — base da Taxologia dos analogismos."),
 "teaticologia": lo("Teaticologia",1898,"*Atentemos à Teaticologia. A prova da teoria está na prática.*"),
 "tecnica-do-trinomio-automotivacao-trabalho-lazer": src("Homo sapiens reurbanisatus","hsr","cap. 138",354,"O *trinômio* da vivência humana é composto pela automotivação, o trabalho e o lazer."),
 "trafor-onipresente": lo("Trafor",1945,"*Trafor: talento cosmoético.* O trafor, mesmo elaborado, é virtude."),
 "vida-programada": src("200 Teáticas da Conscienciologia","200teat","cap. 133",153,"Antes de a vida humana estar programada nos genes, já estava pré-programada, em parte, em certas maxiproéxis, pelos paragenes."),
 "vida-humana": lo("Vida",2012,"Para a conscin lúcida, a vida humana é dia primaveril; para a conscin obtusa, é noite invernal."),
}
CONV = {k:v for k,v in CONV.items() if v}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "aconchego-botanico": R("aconchegar-se à Natureza","[[vida-ecologica]] · [[autovivencia]]"),
 "alcova-blindada": R("alcova blindada energeticamente","[[alcova-contaminada]] · [[trilha-energetica]]"),
 "alcova-contaminada": R("alcova sem higiene consciencial","[[alcova-blindada]] · [[trilha-energetica]]"),
 "alienacao": R("indiferentismo à Cosmoética/Socin","[[autovendagem]] · [[mesmexis]]"),
 "ancoragem-consciencial-externa": R("fixação intrafísica pelo soma","[[fixacao]] · [[autocontingenciamento]]"),
 "animal-humano": R("conscin rendida aos primórdios instintivos","[[alienacao]] · [[vida-mundana]]"),
 "anomia": R("caos por dissolução das normas","[[alienacao]] · [[industria-paralela]]"),
 "antiacaso": R("ocorrência imprevista, malinterpretada","[[fatologia]] · [[vida-programada]]"),
 "aparencia": R("dimensão superficial e ilusória","[[falsidade-objetal]] · [[pseudobjetividade]]"),
 "articulacao-social": R("articular relações sociais","[[forca-presencial]] · [[condominio-cognopolitano]]"),
 "autoconsciexiabilidade-retrocognitiva": R("euforin retrocognitiva avançada","[[autovivencia]] · [[posicionamento-pre-dessomatico]]"),
 "autocontingenciamento": R("condição limitativa temporária","[[ancoragem-consciencial-externa]] · [[autovivencia]]"),
 "automovel": R("veículo de transporte humano","[[objeto-ajustado]] · [[funcionalidade]]"),
 "autorganizacao-livre": R("aplicar posses com inteligência","[[poupanca-existencial]] · [[rotina-util]]"),
 "autovendagem": R("acomodação cega a ideologia","[[alienacao]] · [[autovivencia]]"),
 "autovivencia": R("desfrutar/viver a existência humana","[[vida-humana]] · [[teaticologia]]"),
 "bairrismo": R("visão estreita do patriotismo","[[exilado-na-propria-patria]] · [[alienacao]]"),
 "behaviorismo": R("restrição psicológica ao comportamento","[[conscin-eletronotica]] · [[culturologia]]"),
 "bem": R("propriedade que satisfaz necessidades","[[poupanca-existencial]] · [[autorganizacao-livre]]"),
 "bibliopola": R("vendedor de livros/saber","[[culturologia]] · [[objeto-ajustado]]"),
 "biofilia": R("preocupação prioritária com a vida humana","[[biofilia-monopolizadora]] · [[longevidade-produtiva]]"),
 "biofilia-monopolizadora": R("biofilia excessiva (anti-evolutiva)","[[biofilia]] · [[alienacao]]"),
 "chao": R("superfície onde se vive a existência","[[palco-existencial]] · [[terra-de-todos]]"),
 "cloroformio-popular": R("cultura que aliena o povo acomodado","[[alienacao]] · [[mesmexis]]"),
 "cognopolita": R("habitante da Cognópolis","[[condominio-cognopolitano]] · [[gratificacao-cognopolita]]"),
 "compensacao-mentalsomatica": R("compensar perdas do soma pelo mentalsoma","[[longevidade-produtiva]] · [[fase-existencial-conclusiva]]"),
 "condominio-cognopolitano": R("reunião de moradia/pesquisa/ensino","[[cognopolita]] · [[residencia-proexogenica]]"),
 "confrontacao-urbanistica": R("cotejo entre cidades","[[condominio-cognopolitano]] · [[culturologia]]"),
 "conscin-eletronotica": R("vida sob a ótica da Ciência Convencional","[[behaviorismo]] · [[culturologia]]"),
 "conscin-frutariana": R("conscin de dieta frutariana","[[vida-ecologica]] · [[suprimento-vital]]"),
 "conscin-large": R("conscin doadora e filantrópica","[[bem]] · [[realizacao-humana]]"),
 "culturologia": R("ciência dos costumes/tradições","[[neomesologia]] · [[mimeticologia]]"),
 "dardanologia": R("ciência da destruição de excedentes","[[esbanjamento-consciencial]] · [[industria-paralela]]"),
 "deslanche-existencial": R("desenvolvimento de nova etapa existencial","[[fase-existencial-conclusiva]] · [[neopatamar-libertario]]"),
 "efeito-macho-femea": R("agente gerador/mantenedor da vida","[[reproducao-intrafisica]] · [[vida-humana]]"),
 "esbanjamento-consciencial": R("desperdício de recursos/ECs","[[fartura]] · [[poupanca-existencial]]"),
 "espetacularizacao": R("transformar manifestação em espetáculo","[[aparencia]] · [[cloroformio-popular]]"),
 "exigencia-da-vida-humana": R("recurso necessário à vida humana","[[suprimento-vital]] · [[neomesologia]]"),
 "exilado-na-propria-patria": R("conscin assentada no Cosmos como pátria","[[bairrismo]] · [[terra-de-todos]]"),
 "falsidade-objetal": R("falsidade de objeto/realidade","[[aparencia]] · [[pseudobjetividade]]"),
 "fartura": R("possuir além do suficiente (fartura de ECs)","[[esbanjamento-consciencial]] · [[suprimento-vital]]"),
 "fase-existencial-conclusiva": R("organização do período final da vida","[[posicionamento-pre-dessomatico]] · [[compensacao-mentalsomatica]]"),
 "fatologia": R("ciência dos fatos","[[antiacaso]] · [[realidade-relevante]]"),
 "fixacao": R("tornar firme/estável em local preciso","[[ancoragem-consciencial-externa]] · [[objeto-ajustado]]"),
 "forca-presencial": R("magnetismo da holosfera pessoal","[[ilha-de-consciencialidade]] · [[articulacao-social]]"),
 "fronteirico-dessomatico": R("conscin no limiar da dessoma","[[posicionamento-pre-dessomatico]] · [[fase-existencial-conclusiva]]"),
 "funcionalidade": R("qualidade da função prática","[[objeto-ajustado]] · [[rotina-util]]"),
 "gratificacao-cognopolita": R("vivências gratificantes do cognopolita","[[cognopolita]] · [[condominio-cognopolitano]]"),
 "holopensene-existencial": R("atmosfera de vida e trabalho","[[palco-existencial]] · [[ilha-de-consciencialidade]]"),
 "ideal-existencial": R("tornar melhor a vida na vigília","[[realizacao-humana]] · [[autovivencia]]"),
 "ilha-de-consciencialidade": R("holopensene de isolamento cosmoético","[[forca-presencial]] · [[holopensene-existencial]]"),
 "imagetica": R("ciência das imagens (Cosmovisiologia)","[[aparencia]] · [[culturologia]]"),
 "impossibilidade-natural": R("o infactível por natureza","[[relatividade]] · [[realidade-relevante]]"),
 "inacabamento-pessoal": R("frustração pelo inacabamento intrafísico","[[deslanche-existencial]] · [[pendencia]]"),
 "industria-paralela": R("economia anticosmoética da exploração","[[anomia]] · [[falsidade-objetal]]"),
 "jubileu-evolutivo": R("solenidade comemorativa evolutiva","[[realizacao-humana]] · [[longevidade-produtiva]]"),
 "liturgia-natural": R("viver a experiência intrafísica autoconsciente","[[rotina-util]] · [[autovivencia]]"),
 "longevidade-produtiva": R("longevidade com atividade fecunda","[[compensacao-mentalsomatica]] · [[poupanca-existencial]]"),
 "maquina-consciencial": R("conscin vista como máquina existencial","[[automovel]] · [[funcionalidade]]"),
 "meio-de-sobrevida": R("recurso de prolongar a vida","[[suprimento-vital]] · [[longevidade-produtiva]]"),
 "mesmexis": R("mesmice existencial, neofóbica","[[alienacao]] · [[cloroformio-popular]]"),
 "mimeticologia": R("ciência das repetições/imitações","[[culturologia]] · [[mesmexis]]"),
 "neomesologia": R("relações dos seres com o meio","[[culturologia]] · [[exigencia-da-vida-humana]]"),
 "neopatamar-libertario": R("nova condição libertária na evolução","[[deslanche-existencial]] · [[realizacao-humana]]"),
 "normalizacao": R("voltar ao estado normal","[[rotina-util]] · [[funcionalidade]]"),
 "objeto-ajustado": R("coisa material ajustada ao holopensene","[[funcionalidade]] · [[automovel]]"),
 "onus-da-infancia": R("preço da consciex para renascer","[[vida-humana]] · [[fronteirico-dessomatico]]" if False else "[[vida-humana]] · [[autocontingenciamento]]"),
 "palco-existencial": R("ambiente intrafísico da proéxis","[[holopensene-existencial]] · [[chao]]"),
 "peca-unica": R("unidade singular do conjunto","[[realizacao-humana]] · [[trafor-onipresente]]"),
 "pendencia": R("assunto pendente de solução","[[inacabamento-pessoal]] · [[normalizacao]]"),
 "poder-de-permanencia": R("capacidade de perdurar","[[longevidade-produtiva]] · [[realizacao-humana]]"),
 "posicionamento-pre-dessomatico": R("posição definida antes da dessoma","[[fase-existencial-conclusiva]] · [[fronteirico-dessomatico]]"),
 "poupanca-existencial": R("aplicar teaticamente os bens","[[autorganizacao-livre]] · [[bem]]"),
 "pre-intermissivista": R("conscin pré-serenona sem CI","[[autoconsciexiabilidade-retrocognitiva]] · [[deslanche-existencial]]"),
 "pseudobjetividade": R("imprecisão da forma/aparência","[[aparencia]] · [[falsidade-objetal]]"),
 "realidade-relevante": R("fato do megafoco inarredável","[[fatologia]] · [[impossibilidade-natural]]"),
 "realizacao-humana": R("tornar real/concreto na vida","[[ideal-existencial]] · [[peca-unica]] · [[jubileu-evolutivo]]"),
 "relatividade": R("verdade relativa de ponta","[[impossibilidade-natural]] · [[realidade-relevante]]"),
 "reproducao-intrafisica": R("reproduzir corpos (não consciências)","[[efeito-macho-femea]] · [[onus-da-infancia]]"),
 "residencia-proexogenica": R("moradia funcional (Proexarium)","[[condominio-cognopolitano]] · [[holopensene-existencial]]"),
 "rotina-util": R("sequência diária útil e cosmoética","[[autorganizacao-livre]] · [[normalizacao]] · [[liturgia-natural]]"),
 "sintese-da-vida": R("síntese das retrovidas no polinômio vital","[[autovivencia]] · [[vida-humana]]"),
 "substituicao-programada": R("deslocar/substituir pessoa programadamente","[[vida-programada]] · [[normalizacao]]"),
 "suprimento-vital": R("matéria/energia que mantém a vida","[[fartura]] · [[meio-de-sobrevida]] · [[exigencia-da-vida-humana]]"),
 "taxologia-dos-analogismos": R("ciência dos analogismos lógicos","[[fatologia]] · [[teaticologia]]"),
 "teaticologia": R("ciência da técnica de viver","[[teatica]] · [[tecnica]] · [[autovivencia]]"),
 "tecnica-do-trinomio-automotivacao-trabalho-lazer": R("interfusão automotivação-trabalho-lazer","[[tecnica]] · [[rotina-util]]"),
 "tecnica": R("habilidade especial de fazer melhor","[[teaticologia]] · [[funcionalidade]]"),
 "teoria-dos-7-ces": R("fórmula dos elementos básicos da vida humana","[[exigencia-da-vida-humana]] · [[suprimento-vital]]"),
 "terra-de-todos": R("emprego livre do planeta por todos","[[exilado-na-propria-patria]] · [[chao]]"),
 "tirateima-do-intermissivista": R("técnica de autopersuadir-se da imortalidade","[[autovivencia]] · [[pre-intermissivista]]"),
 "trafor-onipresente": R("traço-força essencial onipresente","[[peca-unica]] · [[realizacao-humana]]"),
 "trilha-energetica": R("rastro de ECs deixado pela pessoa","[[alcova-blindada]] · [[forca-presencial]]"),
 "vida-ecologica": R("existência organizada ecologicamente","[[aconchego-botanico]] · [[suprimento-vital]]"),
 "vida-humana": R("estágio breve na dimensão intrafísica","[[autovivencia]] · [[vida-mundana]] · [[sintese-da-vida]]"),
 "vida-mundana": R("vida da consciex ressomada no mundano","[[vida-humana]] · [[alienacao]]"),
 "vida-programada": R("existência multidimensional planejada","[[substituicao-programada]] · [[antiacaso]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
