# -*- coding: utf-8 -*-
ESP = "Holomaturologia"
A = "[[holomaturidade]]"
def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "almas-gemeas": lo("Romantismo",1775,"Não existem **almas gêmeas**: esse conceito foi gerado pelo romantismo patológico da Socin."),
 "amplificador-da-consciencialidade": src("200 Teáticas da Conscienciologia","200teat","cap. 8",28,"Em holomaturologia, a meta fundamental é a consciência tornar-se *amplificador lúcido da consciencialidade* nos ambientes intra e extrafísicos."),
 "auditoria-da-pancognicao": lo("Pancognição",1436,"A **pancognição** mais séria nasce da Cosmoconsciência; a pancognição é a mesma holocognição evolutiva."),
 "autoconsciencialidade": lo("Autoconsciencialidade",205,"*Autocura é autoconsciencialidade.* A autoconsciencialidade é o eterno vento favorável."),
 "autocontrole": lo("Autocontrole",208,"O controle máximo de si mesmo começa sempre pela autopensenidade linear de alta **reflexão.**"),
 "autodiscernimento": lo("Autodiscernimento",227,"*Autodiscernimento: essência mentalsomática. Autodiscernimento: distinção pensenizada.*"),
 "autoimperdoador": dac("Desencaramujologia",570,"O autoimperdoador sincero é inflexível: tudo muda quando se acaba com o ego exorbitante — ocorre o egocídio."),
 "autolucidez-consciencial": lo("Autolucidez",244,"A autocompreensão leva o princípio consciencial à autolucidez, e a autolucidez leva a consciência vulgar à condição de Consciex Livre (CL)."),
 "bussola-intraconsciencial": src("Homo sapiens reurbanisatus","hsr","cap. 92",258,"A expressão *bússola consciencial* é neologismo técnico da Holomaturologia."),
 "coerenciologia": dac("Autoconsistenciologia",274,"A *consistência* é o caráter do que é consistente, com coerência racional e lógica razoável."),
 "compreensibilidade": lo("Compreensibilidade",453,"*Compreender é fácil.* Vivenciar a **compreensão da ideia** é mais difícil."),
 "consciencia-cosmoetica": lo("Cosmoética",535,"A Cosmoética é a *unidade de medida* e a maior força potencializadora do autodiscernimento. *Conscin sem Cosmoética é soma sem consciência.*"),
 "conscin-organizadora": lo("Organizadora",1408,"A conscin organizadora de uma antologia tem a responsabilidade de exemplificar a capacidade de heterocriticar cosmoeticamente com paradiplomacia."),
 "efeito-da-verpon": lo("Verpon",2003,"A verpon é o rolo compressor da **hiperacuidade.**"),
 "escala-da-discricao": lo("Discrição",650,"A primeira manifestação sutil da erudição de uma conscin é a **discrição.**"),
 "gratidao": lo("Gratidão",933,"A conscin **minipeça assistencial** lúcida não labora esperando gratidão; a gratidão sincera é modalidade sofisticada de recompensa."),
 "holanalise-da-conscin": src("Homo sapiens pacificus","hsp","cap. 40",155,"A *holanálise da conscin* é a avaliação evolutiva máxima, exaustiva, da consciência intrafísica por si mesma, via reações centrífugas da personalidade."),
 "holofilosofia": lo("Holofilosofia",970,"O melhor sistema filosófico é a autovivência teática da **assistencialidade interconsciencial**, em qualquer dimensão, considerando fraternalmente todos os princípios conscienciais."),
 "impessoalizacao": lo("Impessoalização",1021,"O universalismo da fraternidade teática impessoaliza o **ego** da personalidade superior, por meio da interassistencialidade."),
 "incompatibilidade-ciencia-religiao": src("Homo sapiens pacificus","hsp","cap. 310",853,"A Ciência, diferente da Religião, fundamenta-se em hipóteses, teorias, pesquisas e repesquisas, através de refutações continuadas."),
 "incompletude": dac("Infanciologia",796,"Saber pouco é a pior incompletude existencial. *A ignorância degrada.*"),
 "intencionalidade-continuada": lo("Intencionalidade",1075,"A *unidade de medida* da intencionalidade é a **Autocosmoética**; a sua intencionalidade constrói a sua vida."),
 "intencionologia": lo("Intencionologia",1076,"A consciência lúcida, líder interassistencial, torna-se *carvão* ao adentrar a Baratrosfera e revela-se *diamante* na Comunex Evoluída, sempre com a intenção de acolher e instruir."),
 "inutilogia": dac("Inutilogia",855,"As inutilidades onipresentes constituem um *rolo compressor* na intimidade e na exterioridade da vida das conscins."),
 "jubilo-cosmoetico": src("Homo sapiens reurbanisatus","hsr","cap. 429",1033,"O júbilo cosmoético associa-se ao megaparadigma cosmoético — a homeostase cosmoética autoconsciente."),
 "lei-do-maior-esforco": dac("Apriorologia",204,"A *lei do maior esforço evolutivo* abre o caminho do amparo extrafísico: criemos consequências cosmoéticas em todas as manifestações."),
 "macrossenso": src("Homo sapiens pacificus","hsp","cap. 221",571,"Sob a ótica da Mentalsomática, o autodiscernimento é a estrutura da sabedoria — base do macrossenso (hipersensatez teática)."),
 "omissuper": lo("Omissuper",1393,"A omissuper (omissão superavitária) é terapêutica — exemplo é a do anonimato do Ser Serenão; a bisbilhotice ultrapassa a omissuper."),
 "otimizacao-dos-desempenhos": src("700 Experimentos da Conscienciologia","700exp","cap. 474",538,"Quando o motor dos seus esforços na melhoria dos desempenhos é a própria consciência, atinge-se o pique máximo de otimização da trajetória evolutiva."),
 "ponteiro-consciencial": lo("Ponteiro",1586,"Segundo a Holomaturologia, o **ponteiro da bússola consciencial** é o regente da orquestra dos megaatributos da consciência."),
 "positividade-ambigua": lo("Positividade",1591,"Nas tarefas da interassistencialidade devemos manter **pensamentos positivos** mesmo quando a consciência amada ainda não nos compreende."),
 "principio-conscienciocentrico": src("Homo sapiens reurbanisatus","hsr","cap. 2",29,"O termo *conscienciocêntrico* é neologismo técnico da Conscienciocentrologia — base das instituições conscienciocêntricas."),
 "principio-da-prioridade-compulsoria": lo("Prioridade",1627,"Quem identifica mais prioridade no **processo evolutivo** das consciências acerta mais na interassistencialidade."),
 "principio-filosofico": src("Homo sapiens reurbanisatus","hsr","cap. 329",839,"O universalismo é o princípio filosófico magno, fundamentando todos os demais princípios evolutivos."),
 "racionalidade-paracientifica": dac("Introdução",39,"A aplicação da racionalidade paracientífica a todo detalhe do Cosmos (Tudologia) exige neoferramentas linguísticas (Neologia)."),
 "radicalismo": lo("Radicalismo",1689,"Criar problemas, indagações e autorreflexões positivas em outrem é a maior demonstração do **radicalismo cosmoético**, evolutivo, interassistencial."),
 "reconhecimento": lo("Reconhecimento",1709,"A conscin consciencióloga, ao dominar o autoparapsiquismo, não procura o reconhecimento intrafísico temporal, mas objetiva ser vista pelos evoluciólogos do seu grupo."),
 "redutor-do-autodiscernimento": src("Homo sapiens pacificus","hsp","cap. 222",573,"O *redutor do autodiscernimento* (neologismo técnico da Holomaturologia) é o agente que diminui a autolucidez, intelecção, racionalidade e elaboração lógica da pensenização."),
 "sobrepairamento": lo("Sobrepairamento",1844,"**Sobrepairamento** não é *boavidismo*, e sim trabalho evolutivo; com ele tudo tende a melhorar, sobretudo ao se realizar o autoinventariograma."),
 "trinomio-da-holomaturidade": src("Manual da Proéxis","proexis","cap. 23",93,"O trinômio racionalidade-discernimento-holomaturidade expressa a homeostase no emprego do mentalsoma."),
 "primeiro-discernimento": src("700 Experimentos da Conscienciologia","700exp","cap. 166",230,"O primeiro megamito é o da perfeição; aceitar pacificamente as impossibilidades humanas dá ao conscienciólogo maior discernimento e serenidade."),
 "incompletude2": None,
}
CONV = {k:v for k,v in CONV.items() if v}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "almas-gemeas": R("mito romântico sem realidade evolutiva","[[residuo-mitologico]] · [[jogo-da-religiao]]"),
 "amplificador-da-consciencialidade": R("meta: amplificar a consciencialidade","[[autolucidez-consciencial]] · [[megabrangencia]]"),
 "antinorma-da-conscienciologia": R("encarar frontalmente a norma vigente","[[radicalismo]] · [[contestacao-intelectual]]"),
 "antirretilinearidade-consciencial": R("autopensenidade não-retilínea","[[autocontrole]] · [[bussola-intraconsciencial]]"),
 "auditoria-da-pancognicao": R("objetivo magno: pancognição","[[holofilosofia]] · [[macrossenso]]"),
 "auge-consciencial": R("ponto pinacular da consciência lúcida","[[autolucidez-consciencial]] · [[omniproporcionalidade]]"),
 "autoconsciencialidade": R("nível de autoconhecimento","[[autolucidez-consciencial]] · [[holanalise-da-conscin]]"),
 "autocontrole": R("equilíbrio e estabilidade da conscin","[[autocontrole]]" if False else "[[autoconsciencialidade]] · [[bussola-intraconsciencial]]"),
 "autodiscernimento": R("capacidade superior de distinção","[[autolucidez-consciencial]] · [[primeiro-discernimento]] · [[redutor-do-autodiscernimento]]"),
 "autoimperdoador": R("inflexível consigo (egocídio)","[[autocontrole]] · [[consciencia-cosmoetica]]"),
 "autolucidez-consciencial": R("autoconsciencialidade clara e aguda","[[autoconsciencialidade]] · [[autodiscernimento]]"),
 "bussola-intraconsciencial": R("orientação rumo à evolução","[[ponteiro-consciencial]] · [[autocontrole]]"),
 "coerenciologia": R("ciência da coerência consciencial","[[racionalidade-paracientifica]] · [[autodiscernimento]]"),
 "compreensibilidade": R("nível de percuciência de quem compreende","[[holofilosofia]] · [[autodiscernimento]]"),
 "consciencia-cosmoetica": R("personalidade que vive a Cosmoética","[[consciencia-cosmoetica]]" if False else "[[autodiscernimento]] · [[jubilo-cosmoetico]] · [[intencionalidade-continuada]]"),
 "conscin-organizadora": R("quem organiza/coordena","[[otimizacao-dos-desempenhos]] · [[vida-matematica]]"),
 "contestacao-intelectual": R("oposição racional heterocrítica","[[radicalismo]] · [[antinorma-da-conscienciologia]]"),
 "definitividade": R("condição definitiva imposta às realidades","[[infrangibilidade]] · [[superexatidao]]"),
 "efeito-da-verpon": R("consequência de exemplificar a verpon","[[verdade-antidemagogica]] · [[radicalismo]]"),
 "escala-da-discricao": R("gradação da discrição interassistencial","[[omissuper]] · [[impessoalizacao]]"),
 "frugalidade-complexa": R("condição paradoxal de IE prioritária","[[utilidade-decrescente]] · [[intensidade-existencial]]"),
 "gratidao": R("trafor de quem é grato sem esperar retorno","[[reconhecimento]] · [[impessoalizacao]]"),
 "holanalise-da-conscin": R("avaliação evolutiva exaustiva de si","[[autoconsciencialidade]] · [[auditoria-da-pancognicao]]"),
 "holofilosofia": R("filosofia teática da assistencialidade","[[auditoria-da-pancognicao]] · [[principio-filosofico]]"),
 "imperfectividade": R("o ainda por terminar","[[incompletude]] · [[imperfectividade]]" if False else "[[incompletude]] · [[superexatidao]]"),
 "impessoalizacao": R("tornar impessoal o ego","[[universalismo]] · [[gratidao]]"),
 "incompatibilidade-ciencia-religiao": R("discordância de fundamentação","[[jogo-da-religiao]] · [[principio-filosofico]]"),
 "incompletude": R("realidade faltando alguma parte","[[imperfectividade]] · [[utilidade-decrescente]]"),
 "infrangibilidade": R("condição inquebrável/indestrutível","[[definitividade]] · [[superexatidao]]"),
 "intencionalidade-continuada": R("intenção mantida em alto nível","[[intencionologia]] · [[consciencia-cosmoetica]]"),
 "intencionologia": R("ciência da intenção","[[intencionalidade-continuada]] · [[cosmoetica]]"),
 "intensidade-existencial": R("existência vivida com vigor","[[lei-do-maior-esforco]] · [[otimizacao-dos-desempenhos]]"),
 "intrarticulacao-heuristica": R("identificação heurística máxima","[[holofilosofia]] · [[auditoria-da-pancognicao]]"),
 "inutilogia": R("ciência dos atos inúteis","[[utilidade-decrescente]] · [[frugalidade-complexa]]"),
 "jogo-da-religiao": R("trama implantada na consciência dos fiéis","[[incompatibilidade-ciencia-religiao]] · [[residuo-mitologico]]"),
 "jubilo-cosmoetico": R("exultar pela homeostase cosmoética","[[consciencia-cosmoetica]] · [[sobrepairamento]]"),
 "lei-do-maior-esforco": R("máxima vontade de esforço evolutivo","[[intensidade-existencial]] · [[preco-do-ideal]]"),
 "limite-inteligente": R("demarcação crítica inteligente","[[autocontrole]] · [[escala-da-discricao]]"),
 "macrossenso": R("hipersensatez teática","[[autodiscernimento]] · [[auditoria-da-pancognicao]]"),
 "megabrangencia": R("presença vivificadora no Cosmos","[[amplificador-da-consciencialidade]] · [[omniproporcionalidade]]"),
 "obscuridade": R("estado sem lucidez/clareza","[[autolucidez-consciencial]]" "" or "[[autolucidez-consciencial]] · [[residuo-mitologico]]"),
 "omissuper": R("omissão superavitária terapêutica","[[escala-da-discricao]] · [[impessoalizacao]]"),
 "omniproporcionalidade": R("identificar a justa proporção","[[megabrangencia]] · [[limite-inteligente]]"),
 "otimizacao-dos-desempenhos": R("otimizar ao máximo os esforços teáticos","[[intensidade-existencial]] · [[conscin-organizadora]]"),
 "padrao-sempiterno": R("exemplificar perenemente os posicionamentos","[[trinomio-da-holomaturidade]] · [[consciencia-cosmoetica]]"),
 "ponteiro-consciencial": R("indicador das autodecisões","[[bussola-intraconsciencial]] · [[intencionalidade-continuada]]"),
 "positividade-ambigua": R("positividade aparente, errada","[[autodiscernimento]] · [[verdade-antidemagogica]]"),
 "preco-do-ideal": R("valor exigido pela melhor condição evolutiva","[[lei-do-maior-esforco]] · [[intensidade-existencial]]"),
 "primeiro-discernimento": R("atitude inicial de IE (aceitar limites)","[[autodiscernimento]] · [[redutor-do-autodiscernimento]]"),
 "principio-conscienciocentrico": R("convergência conscienciocêntrica","[[principio-filosofico]] · [[holofilosofia]]"),
 "principio-da-prioridade-compulsoria": R("opção única insubstituível","[[escala-da-discricao]]" if False else "[[principio-filosofico]] · [[intencionalidade-continuada]]"),
 "principio-filosofico": R("base filosófica do paradigma","[[holofilosofia]] · [[principio-conscienciocentrico]]"),
 "racionalidade-paracientifica": R("razão teática paracientífica","[[coerenciologia]] · [[autodiscernimento]]"),
 "radicalismo": R("radicalismo cosmoético interassistencial","[[contestacao-intelectual]] · [[antinorma-da-conscienciologia]]"),
 "reconhecimento": R("ratificar/legitimar o mérito","[[gratidao]] · [[impessoalizacao]]"),
 "redutor-do-autodiscernimento": R("agente que reduz a autolucidez","[[autodiscernimento]] · [[primeiro-discernimento]]"),
 "relevalidade": R("ato de relevar com inteligência","[[autocontrole]] · [[sobrepairamento]]"),
 "residuo-mitologico": R("carga de tolices/mitos antigos","[[almas-gemeas]] · [[jogo-da-religiao]]"),
 "sobrepairamento": R("pairar alto, cosmoético","[[impessoalizacao]] · [[jubilo-cosmoetico]]"),
 "superexatidao": R("exatidão máxima possível","[[infrangibilidade]] · [[definitividade]]"),
 "trinomio-da-holomaturidade": R("racionalidade-discernimento-holomaturidade","[[autodiscernimento]] · [[mentalsoma]] · [[padrao-sempiterno]]"),
 "utilidade-decrescente": R("algo a caminho da inutilidade","[[inutilogia]] · [[frugalidade-complexa]]"),
 "verdade-antidemagogica": R("verdade aceita sem demagogia","[[efeito-da-verpon]] · [[radicalismo]]"),
 "vida-matematica": R("existência organizada tecnicamente","[[conscin-organizadora]] · [[otimizacao-dos-desempenhos]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
