# -*- coding: utf-8 -*-
ESP = "Experimentologia"
A = "[[teatica]]"
def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "administracao-da-vida-intelectual": lo("Administração",60,"O **neoconstructo** para a melhoria da administração dos documentos mentaissomáticos pode ser mais funcional do que o contexto da maior obra técnica."),
 "aprofundamento-da-pesquisa": lo("Aprofundamento",133,"A minicompreensão das coisas, parcial, gera os **pseudossábios**; toda pesquisa exige aprofundamento e confirmação."),
 "arquivologia": lo("Arquivologia",140,"Você vale a sua **Arquivologia Vivencial.** A Ciência da acumulação de dados é a Arquivologia."),
 "autestigmatizacao": src("Homo sapiens pacificus","hsp","cap. 64",201,"A opção pela carreira militar é autestigmatização consciente."),
 "autodisposicao": lo("Autodisposição",232,"Se a pessoa está bem disposta, vê as realidades com mais detalhismo e coerência; se cansada, enxerga de modo segmentado, não inteiriço."),
 "autopesquisologia": lo("Autopesquisologia",267,"**Autopesquisologia** é um dos sinônimos mais fidedignos da *Autossabedoria*; iludimo-nos mais sobre nós mesmos do que sobre os outros."),
 "autossuperacao-especifica": lo("Autossuperação",302,"Quanto mais depressa superarmos a frustração, buscando o **refazimento** ou a autossuperação, mais rápida a troca do megadeslize pelo miniacerto."),
 "balao-de-ensaio": lo("Ensaio",723,"O *ensaio* é a análise, o **aforismo** é a síntese."),
 "binomio-autoconscienciometrologia-autopesquisologia": dac("Holopensenologia",767,"Importa indagar a qualidade do holopensene em que se lê — teste singular e realista de autopesquisa."),
 "compactacao": src("Projeciologia","proj","cap. 159",350,"A reunião compacta das ideias faz os alvos mais instigantes, mais amplos e menos difíceis de serem atingidos."),
 "compatibilidade-automotivacao-trabalho": lo("Autodiscernimento",229,"O *trinômio automotivação-trabalho-lazer* dinamiza a evolução consciencial desde que haja autodiscernimento."),
 "corpus-da-conscienciologia": lo("Conscienciologia",493,"O domínio da autocompreensão teática do *corpus* de princípios da Conscienciologia ocorre quando a conscin adquire a **autofiex**, na semiconsciexialidade."),
 "descrenciologia": lo("Descrenciologia",604,"*Toda autovivência gera experiência. Toda crença gera desavença.* A Descrenciologia vivenciada elimina idolatria e fanatismo."),
 "detalhismo": lo("Detalhismo",632,"A verdadeira **cosmovisão** começa a funcionar pelo detalhismo; para quem pesquisa, o detalhismo não é formalismo."),
 "dia-da-cobaia": lo("Conscin-Cobaia",501,"Quem se esquiva de ser **conscin-cobaia** sadia na IC pode acabar sendo conscin-cobaia quando doente no Hospital."),
 "dosagem": lo("Dosimetria",668,"O melhor da conscin lúcida é não exagerar na dosagem do remédio, qualquer remédio."),
 "estafa-intelectual": src("200 Teáticas da Conscienciologia","200teat","cap. 139",159,"Pela paraprofilaxia, é inteligente combater a estafa intelectual com esforço máximo em todas as frentes da execução da proéxis."),
 "fatuistica": src("Homo sapiens reurbanisatus","hsr","cap. 338",865,"O termo *fatuística* é neologismo técnico da Experimentologia — a Ciência dos fatos."),
 "fonte-de-assombro": lo("Assombro",166,"A consciência só é convidada a visitar a Comunex Evoluída quando já não mais se assombra com as realidades do Cosmos."),
 "hipotese": src("Homo sapiens reurbanisatus","hsr","cap. 47",158,"O feto de ideia (hipótese) não é a ideia madura (teoria); em megapensene trivocabular: *Hipótese significa limitação.*"),
 "inexistencia": lo("Inexistência",1044,"*Inexiste beleza anticosmoética. Inexiste alegria baratrosférica.*"),
 "interacao-analise-sintese": lo("Análise",101,"Toda grande síntese nasce de análise: a **análise** é a mãe da *síntese*; a síntese é a destilação da análise."),
 "lacuna-da-formacao-cultural": src("Homo sapiens reurbanisatus","hsr","cap. 250",651,"A autorganização diminui o percentual de erros de qualquer pessoa motivada, independentemente do sexo ou da formação cultural."),
 "linha-de-montagem": lo("Megagescon",1251,"A conscin escritora veterana estabelece a **linha de montagem** da megagescon, organizando a cronologia dos autesforços e a prospectiva da produtividade."),
 "musa-cientifica": src("200 Teáticas da Conscienciologia","200teat","cap. 149",169,"Na intrafisicologia, certas *vedetes energéticas* atuam em meio a uma primener, ao modo da diva e da musa de um segmento social."),
 "paracientista": lo("Extrafisicalidade",835,"Toda consciex, ao ascender na Escala Evolutiva, torna-se **paracientista cosmoético**; o paracientista serve ao público e ao parapúblico."),
 "pesquisa-dos-50-prefacios": src("700 Experimentos da Conscienciologia","700exp","cap. 276",340,"Pela Técnica das 50 Vezes Mais, se a tarefa parece concluída com menos de 50 vezes dos próprios esforços, sinta isso como autocorrupção grosseira."),
 "pesquisador-conscienciologico": lo("Mateologia",1223,"Ao **pesquisador conscienciológico**, o *mistério* foi substituído pela Mateologia."),
 "pesquisador-independente": lo("Pesquisador",1553,"A conscin pesquisadora independente alcança a tenepes, a autodesperticidade e a autofiex mais depressa; a experimentação pessoal é imitável, mas intransferível."),
 "planilha-tecnica": src("700 Experimentos da Conscienciologia","700exp","cap. 17",81,"A planilha de abordagem científica (Técnica da Pesquisa Conscienciológica) conduz o pesquisador às próprias conclusões."),
 "repeticao-paciente": src("Projeciologia","proj","cap. 61",169,"O autodiscernimento entre um estado e outro só é alcançado com a repetição paciente e exaustiva das experiências."),
 "singularidade-plural": lo("Pluralidade",1569,"A **singularidade** existe porque ninguém é igual ao outro; o *plural* é a soma dos singulares."),
 "sintese-conclusiva": lo("Compreensões",454,"São mais difíceis de alcançar: o temperamento pessoal, a síntese mais conclusiva e o monossílabo mais adequado."),
 "sintese-da-conscienciologia": lo("Conscienciologia",491,"*Conscienciologia: síntese cósmica.*"),
 "taxologia-das-sinteses": lo("Sínteses",1843,"Quem não pode explicitar o núcleo da comunicação num parágrafo de 10 linhas deve estudar mais as técnicas das sínteses autopensênicas."),
 "taxologia-das-falhas": lo("Falhas",847,"É preciso ter mais cuidado ao assistir às **consciências falhas de afeição.**"),
 "tecnica-da-circularidade": lo("Circularidade",413,"A *técnica da circularidade* do processo autocognitivo leva à **pluralização** das abordagens pesquisísticas."),
 "tecnica-da-exaustividade": lo("Exaustividade",816,"A **técnica da exaustividade** lógica, aplicada autocriticamente com a Conscienciometria, aponta nossos trafares, minis e megas."),
 "teoria-do-megafoco-profissional": lo("Megafoco",1248,"Cada consciência é qualificada pela qualidade do seu **megafoco evolutivo**; o megafoco é o próprio alvo."),
 "triatleta-conscienciologico": lo("Laboratório",1143,"O **Laboratório Conscienciológico** é uma solitária mentalsomática temporária — campo do triatleta (teática, parapsiquismo, energias)."),
 "soltura-mentalsomatica": src("200 Teáticas da Conscienciologia","200teat","cap. 181",201,"Pela holossomática, a soltura do holochacra foge à condição coincidente dos veículos da consciência intrafísica — base da soltura mentalsomática."),
 "taxologia-das-analises": src("200 Teáticas da Conscienciologia","200teat","cap. 80",100,"Na holocarmologia, as análises evolutivas do egocarma vêm antes das análises conscienciométricas da grupocarmologia e da policarmologia."),
}
CONV = {k:v for k,v in CONV.items() if v}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "abordagem-consciencial": R("contato/acesso a determinada consciência","[[paracientista]] · [[pesquisa-curiosa]]"),
 "acrasia": R("fraqueza de vontade incontinente","[[escapismo]] · [[espera-inutil]]"),
 "acumulabilidade": R("capacidade de acumular dados/experiências","[[arquivologia]] · [[fatuistica]]"),
 "administracao-da-vida-intelectual": R("gerir o trabalho intelectual","[[linha-de-montagem]] · [[planilha-tecnica]]"),
 "aprofundamento-da-pesquisa": R("intensificar os procedimentos da pesquisa","[[tecnica-da-exaustividade]] · [[limite-da-pesquisa]]"),
 "arquivologia": R("ciência dos arquivos e bancos de dados","[[acumulabilidade]] · [[registro-eterno]]"),
 "autestigmatizacao": R("ação que estigmatiza a si própria","[[escapismo]] · [[acrasia]]"),
 "autodisposicao": R("estado de ânimo/predisposição","[[compatibilidade-automotivacao-trabalho]] · [[estafa-intelectual]]"),
 "autopesquisologia": R("ciência da autopesquisa","[[binomio-autoconscienciometrologia-autopesquisologia]] · [[autopesquisa]]"),
 "autossuperacao-especifica": R("burilamento por superação pontual","[[gargalo-operacional]] · [[autodisposicao]]"),
 "balao-de-ensaio": R("ensaio inicial de pesquisa","[[hipotese]] · [[fruto-experimental]]"),
 "binomio-autoconscienciometrologia-autopesquisologia": R("autoconscienciometria × autopesquisa","[[autopesquisologia]] · [[conscienciometria]]"),
 "compactacao": R("reunião compacta das ideias","[[sintese-conclusiva]] · [[interacao-analise-sintese]]"),
 "compatibilidade-automotivacao-trabalho": R("coincidência automotivação↔trabalho","[[autodisposicao]] · [[teoria-do-megafoco-profissional]]"),
 "complicador": R("neofator que complica a pesquisa","[[gargalo-operacional]] · [[limite-da-pesquisa]]"),
 "conceito-de-conscienciologia": R("constructo definidor da Ciência","[[corpus-da-conscienciologia]] · [[sintese-da-conscienciologia]]"),
 "confrontologia": R("ciência do confronto/cotejo","[[interacao-analise-sintese]] · [[taxologia-das-analises]]"),
 "corpus-da-conscienciologia": R("conjunto coeso de princípios","[[conceito-de-conscienciologia]] · [[sintese-da-conscienciologia]] · [[portfolio-da-conscienciologia]]"),
 "corredor-heuristico": R("fluxo de condições da descoberta","[[fonte-de-assombro]] · [[iniciativa-planetaria-pioneira]]"),
 "descrenciologia": R("ciência da descrença (PD vivenciado)","[[pesquisador-independente]] · [[teste-conscienciologico]]"),
 "detalhismo": R("valor funcional das circunstâncias mínimas","[[tecnica-da-exaustividade]] · [[nuanca]]"),
 "dia-da-cobaia": R("data da autoconscientização como cobaia","[[paracientista]] · [[pesquisador-conscienciologico]]"),
 "dosagem": R("medir atitude/palavra para controlar efeitos","[[detalhismo]] · [[teste-conscienciologico]]"),
 "escapismo": R("fugir à realidade/rotina","[[acrasia]] · [[espera-inutil]]"),
 "escolha-evolutiva": R("selecionar entre opções com critério","[[autodisposicao]] · [[teoria-do-megafoco-profissional]]"),
 "espera-inutil": R("inércia de braços cruzados","[[escapismo]] · [[acrasia]]"),
 "estafa-intelectual": R("esgotamento no trabalho mental","[[autodisposicao]] · [[administracao-da-vida-intelectual]]"),
 "eumatia": R("facilidade de aprender","[[pesquisa-curiosa]] · [[soltura-mentalsomatica]]"),
 "experiencia-compartilhada": R("vivência conjunta de várias consciências","[[paracientista]] · [[abordagem-consciencial]]"),
 "extraconscienciologia": R("ciência do extraconsciencial","[[interconscienciologia]] · [[paracientista]]"),
 "fatuistica": R("ciência dos fatos (neologismo da Experimentologia)","[[acumulabilidade]] · [[registro-eterno]]"),
 "fonte-de-assombro": R("o que gera assombro investigativo","[[corredor-heuristico]] · [[iniciativa-planetaria-pioneira]]"),
 "fontificacao": R("tornar fonte um recurso secundário","[[autopesquisologia]] · [[arquivologia]]"),
 "fruto-experimental": R("resultado do esforço experimental","[[balao-de-ensaio]] · [[teste-conscienciologico]]"),
 "gargalo-operacional": R("decisões dramáticas de um empreendimento","[[autossuperacao-especifica]] · [[complicador]]"),
 "hierarquizacao": R("organizar em ordem hierárquica","[[taxologia]] · [[taxologia-das-analises]]"),
 "hipotese": R("suposição não-improvável","[[balao-de-ensaio]] · [[teste-conscienciologico]]"),
 "incompatibilidade-da-conscienciologia": R("discordância de fundamentação","[[descrenciologia]] · [[paradigma-consciencial]]"),
 "inexistencia": R("ausência de realidade suposta","[[hipotese]] · [[mitoclastia]]" if False else "[[hipotese]] · [[fonte-de-assombro]]"),
 "iniciativa-planetaria-pioneira": R("verpon/neoteática pioneira","[[corredor-heuristico]] · [[primeira-onda]]"),
 "interacao-analise-sintese": R("conjugar análise e síntese","[[compactacao]] · [[sintese-conclusiva]] · [[taxologia-das-sinteses]]"),
 "interconscienciologia": R("ciência das manifestações entre consciências","[[extraconscienciologia]] · [[experiencia-compartilhada]]"),
 "lacuna-da-formacao-cultural": R("falha no desenvolvimento intelectual","[[primarismo-tecnico]] · [[estafa-intelectual]]"),
 "limite-da-pesquisa": R("raia da pesquisa possível","[[aprofundamento-da-pesquisa]] · [[tecnica-da-exaustividade]]"),
 "linha-de-montagem": R("disposição esquemática de recursos","[[administracao-da-vida-intelectual]] · [[planilha-tecnica]]"),
 "mateologistica": R("ciência do que está fora da experiência","[[pesquisador-conscienciologico]] · [[fonte-de-assombro]]"),
 "musa-cientifica": R("personalidade que inspira a pesquisa","[[pesquisa-curiosa]] · [[fonte-de-assombro]]"),
 "nuanca": R("matiz/gradação fina da realidade","[[detalhismo]] · [[interacao-analise-sintese]]"),
 "nucao": R("aprovar algo (decisão da vontade)","[[escolha-evolutiva]] · [[autodisposicao]]"),
 "omnicompartimentalizacao": R("dividir em compartimentos","[[hierarquizacao]] · [[taxologia]]"),
 "operacao": R("complexo de meios operativos","[[planilha-tecnica]] · [[linha-de-montagem]]"),
 "paracientista": R("pesquisador da consciência (4 corpos)","[[pesquisador-conscienciologico]] · [[triatleta-conscienciologico]] · [[experiencia-compartilhada]]"),
 "parateatica": R("parateoria + paraprática","[[teatica]] · [[paracientista]]"),
 "pesquisa-curiosa": R("investigação de alto envolvimento","[[eumatia]] · [[musa-cientifica]]"),
 "pesquisa-dos-50-prefacios": R("ler 50 prefácios registrando dados","[[tecnica-da-exaustividade]] · [[pesquisador-conscienciologico]]"),
 "pesquisador-conscienciologico": R("pesquisador sem limites cosmoéticos","[[pesquisador-independente]] · [[paracientista]] · [[descrenciologia]]"),
 "pesquisador-independente": R("pesquisa autônoma e livre","[[pesquisador-conscienciologico]] · [[autopesquisologia]]"),
 "planilha-tecnica": R("quadro/programa de medida","[[operacao]] · [[teste-conscienciologico]] · [[conscienciometria]]"),
 "plano-existencial": R("dimensão/região da existência","[[abordagem-consciencial]] · [[extraconscienciologia]]"),
 "portfolio-da-conscienciologia": R("panorâmica das realidades da Ciência","[[corpus-da-conscienciologia]] · [[sintese-da-conscienciologia]]"),
 "primarismo-tecnico": R("calouro sem experiência de trabalho","[[lacuna-da-formacao-cultural]] · [[primeira-onda]]"),
 "primeira-onda": R("movimento inicial de uma novidade","[[iniciativa-planetaria-pioneira]] · [[primarismo-tecnico]]"),
 "registro-eterno": R("assinatura pensênica de toda ação","[[arquivologia]] · [[fatuistica]]"),
 "repeticao-paciente": R("reprisar ações com regularidade","[[tecnica-da-exaustividade]] · [[detalhismo]]"),
 "singularidade-plural": R("evento singular e plural ao mesmo tempo","[[nuanca]] · [[taxologia]]"),
 "sintese-conclusiva": R("síntese relativa, conclusiva no momento","[[interacao-analise-sintese]] · [[taxologia-das-sinteses]]"),
 "sintese-da-conscienciologia": R("síntese cósmica da Ciência","[[corpus-da-conscienciologia]] · [[conceito-de-conscienciologia]]"),
 "sistemata": R("pesquisador especialista em sistemas","[[paracientista]] · [[hierarquizacao]]"),
 "soltura-mentalsomatica": R("máximo abertismo intelectual","[[eumatia]] · [[corredor-heuristico]]"),
 "taxologia-da-seguranca": R("classificação da segurança","[[taxologia]] · [[taxologia-das-falhas]]"),
 "taxologia-das-analises": R("categorias das avaliações","[[taxologia]] · [[interacao-analise-sintese]]"),
 "taxologia-das-falhas": R("classificação das falhas/erros","[[taxologia]] · [[taxologia-da-seguranca]]"),
 "taxologia-das-sinteses": R("classificação das sínteses","[[taxologia]] · [[sintese-conclusiva]] · [[interacao-analise-sintese]]"),
 "taxologia": R("ciência das classificações","[[taxologia-das-analises]] · [[taxologia-das-sinteses]] · [[taxologia-das-falhas]] · [[hierarquizacao]]"),
 "tecnica-da-circularidade": R("abordagens plurais do mesmo objeto","[[tecnica-da-exaustividade]] · [[interacao-analise-sintese]]"),
 "tecnica-da-exaustividade": R("levar a perquirição às últimas consequências","[[detalhismo]] · [[aprofundamento-da-pesquisa]] · [[tecnica-da-circularidade]]"),
 "teoria-do-megafoco-profissional": R("megafoco como alvo profissional","[[escolha-evolutiva]] · [[compatibilidade-automotivacao-trabalho]]"),
 "teste-conscienciologico": R("método/prova de avaliação","[[planilha-tecnica]] · [[conscienciometria]] · [[hipotese]]"),
 "triatleta-conscienciologico": R("teática + parapsiquismo + energias","[[paracientista]] · [[soltura-mentalsomatica]]"),
 "usabilidade": R("nível de utilização prática","[[operacao]] · [[planilha-tecnica]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
