# -*- coding: utf-8 -*-
ESP = "Conviviologia"
A = "[[conviviologia]]"  # hub

def lo(v,p): return ("Léxico de Ortopensatas", None, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p): return ("Dicionário de Argumentos da Conscienciologia", None, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p): return (book, None, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

# CONV: slug -> (titulo, texto, citacao, linha_fonte)
def C(base, texto):
    titulo, _, cit, fonte = base
    return (titulo, texto, cit, fonte)

CONV = {
 "adversario-ideologico": C(src("200 Teáticas da Conscienciologia","200teat","cap. 114",134), "Pela evoluciologia, evidencia-se o conflito de um grupo ideológico mais primário, ou neófobo, em anteposição a um grupo ideológico mais evoluído, ou neofílico."),
 "aglutinacao-interconsciencial": C(lo("Aglutinação",71), "A *energia consciencial* (EC) é o principal elemento utilizado para gerar a aglutinação interconsciencial, que geralmente tem início na **família nuclear.**"),
 "ajudante-de-algoz": C(lo("Algoz",80), "O **algoz** piora sempre mais que a *vítima.* A bigorna permanece intacta quando o martelo quebra o cabo."),
 "amigo-comum": C(lo("Reciprocidade",1704), "A condição do *duplista* na dupla evolutiva e a do *amigo* na amizade têm em comum a **reciprocidade.**"),
 "amizade-interativa": C(lo("Amizade",89), "A amizade expressa em **ações** é superior à amizade expressa em *palavras.*"),
 "amizade-rarissima": C(lo("Amizade",91), "O vocábulo **raríssima**, da expressão *amizade raríssima*, significa ***autodiscernimento***; a amizade raríssima nasce da **familiaridade.**"),
 "antagonismo-imitacao-evitacao": C(lo("Imitação",1014), "*Imitação: primeira protossabedoria.* A imitação dos **maus costumes** está entre as piores ignorâncias."),
 "anticonscienciologista": C(lo("Anticonscienciologista",115), "A conscin, quando *minidissidente ideológica*, pode regredir, tornando-se **anticonscienciologista**, posicionada convictamente contra o *corpus* de princípios libertários da Conscienciologia."),
 "antipodia-consciencial": C(lo("Antipodia",121), "Quanto mais a **consciência** evolui, mais o seu microuniverso se equilibra, inclusive por antipodia."),
 "binomio-admiracao-discordancia": C(src("200 Teáticas da Conscienciologia","200teat","cap. 25",45), "Pela cosmoética, no binômio admiração-discordância ocorre a *união inteligente dos contrários*, abertura natural para a vivência do universalismo e da fraternidade."),
 "binomio-autoconformismo-autoinconformismo": C(lo("Autoconformismo",204), "*Autoconformismo: medorreia máxima.*"),
 "carga-da-convivialidade": C(lo("Convivialidade",523), "A **convivialidade** é indispensável: as pessoas saem da mediocridade unindo-se aos bem-dotados evolutivamente."),
 "casal-incompleto": C(src("200 Teáticas da Conscienciologia","200teat","cap. 30",50), "Pela experimentologia, os casais classificam-se em 2 categorias quanto à profundidade dos relacionamentos: o casal incompleto e o casal íntimo."),
 "circulo-de-relacoes": C(lo("Paraconvivialidade",1448), "Quem melhora o círculo de **relações intrafísicas** amplia o círculo de relações extrafísicas: há consciências que evocam outras no caminho da evolução."),
 "companhia-constrangedora": C(lo("Companhia",442), "A companhia qualifica a ***consciência.*** Quem não escolhe a **companhia** se desvia."),
 "companhia-eletiva": C(dac("Antinsoniologia",173), "No Cosmos, a primeira companhia eletiva de que você dispõe é você mesmo. Saiba viver com os seus pensenes."),
 "comunidade-conscienciologica-cosmoetica-internacional": C(dac("Multidimensiologia",1017), "A CCCE (Extrafísica) e a CCCI (Internacional) são criações diretas dos Cursos Intermissivos (CIs), ao modo de realidades multidimensionais."),
 "conduta-cosmoetica": C(src("Manual da Proéxis","proexis","cap. 22",90), "Há uma conduta cosmoética fundamental que regra os princípios da megafraternidade: *não ser manipulado nem manipular consciências.*"),
 "conscin-convencional": C(dac("Pseudorraciocinologia",1285), "A *pseudorracionalidade* é a condição da pessoa paradoxal, crente e materialista, com a vida assentada nas lavagens subcerebrais da Ciência Convencional."),
 "conscin-problema": C(lo("Debate",574), "Há imensa diferença entre a **conscin debatedora**, que discute o problema, e a outra, que vive pessoalmente o problema no momento."),
 "convivencia-nociva": C(lo("Convivência",522), "Devemos ter cuidado na **convivência** com aquela pessoa que compreende melhor o seu cachorro do que o próprio irmão."),
 "dependencia-indireta": C(src("Homo sapiens reurbanisatus","hsr","cap. 69",206), "Consoante a Experimentologia, há *dependências* ou coleiras compulsórias do ego — listam-se 13 (alimentar, econômico-financeira etc.)."),
 "elenco-da-conscienciologia": C(src("Homo sapiens reurbanisatus","hsr","cap. 29",95), "A partir da análise do microuniverso das personalidades humanas, encontram-se múltiplos protótipos ou perfis componentes do elenco de consciências das reurbexes."),
 "elogio-controvertivel": C(lo("Elogio",705), "Nenhum **elogio** é um bom conselho. O elogio pode ser a pior *heterocrítica.*"),
 "entrevista-evolutiva": C(src("Homo sapiens pacificus","hsp","cap. 379",972), "O clima interconsciencial dos mais avançados é constituído pela entrevista (projeção-entrevista) do pré-serenão com o Serenão."),
 "estimulo-extrapauta": C(dac("Preservaciologia",1267), "Extrapauta interassistencial: o *feedback* interassistencial de amigo para amigo sobre alguma informação crítica ou privilegiada."),
 "evitacao-da-evitacao": C(lo("Evitação",793), "O mais inteligente é evitar o **bilionário** que não se ruboriza — eliminando o posicionamento de evitação ainda emocional."),
 "exposicao-publica": C(src("700 Experimentos da Conscienciologia","700exp","cap. 459",523), "Acaba a concorrência interpessoal ansiosa, o medo de errar com exposição ao ridículo e a escravidão à opinião pública."),
 "fauna-humana-noturna": C(lo("Fauna",861), "A **fauna humana** de consréus precisa de ajuda."),
 "fusao-social": C(dac("Sociosferologia",1359), "A *fusão social* não é *confusão social*: é saber conviver com todo mundo, não só com o povo da intermissão na Cognópolis (Transafetivologia)."),
 "imitacao-individual": C(lo("Imitação",1014), "*Imitação: primeira protossabedoria.*"),
 "inducao-interconsciencial": C(lo("Indução",1041), "Com uma única **palavra** você pode influir em toda a vida da pessoa."),
 "interassistenciologia": C(lo("Interassistenciologia",1081), "No universo da ***Interassistenciologia***, o acervo dos **donativos** cosmoéticos tem sempre de ser superior à multidão de *promessas* teóricas."),
 "intersubjetividade": C(src("Projeciologia","proj","cap. 01",15), "Não há necessidade de negar o subjetivo ou a intersubjetividade entre as conscins — por exemplo, a da dupla evolutiva."),
 "licao-de-vida": C(lo("Lição",1168), "A primeira lição da sabedoria é a **autexemplificação** cosmoética."),
 "penduricalho-pessoal": C(lo("Adorno",62), "*Adorno: penduricalho extra.*"),
 "plenitude-convivencial": C(lo("Ajuda",75), "*Ajuda: fundamento convivencial.*"),
 "profissional-dificultoso": C(lo("Profissional",1644), "A **qualificação do profissional** vem antes da qualificação da profissão."),
 "relacao-conscin-consciex": C(lo("Interrelação",1104), "A relação interconsciencial, em ordem decrescente, é mais favorável de consciex para consciex, depois de consciex para conscin, de conscin para conscin e, por fim, da conscin para o ser pré-humano."),
 "relacao-transformadora": C(lo("Paraetologia",1457), "Onde o Ser Serenão aparece, ocorre alguma relação transformadora; em sua presença, os assediadores extrafísicos fogem."),
 "reclusao-voluntaria": C(lo("Comunicabilidade",462), "Retrovidas humanas de **reclusão** geram transtornos de comunicação na vida atual."),
 "senso-de-fraternidade": C(lo("Fraternidade",889), "*Fraternidade é sabedoria. Nenhum ato de amor se perde.*"),
 "status": C(lo("Status",1863), "O *status* evolutivo maior é o gabarito da pessoa no universo da **interassistencialidade** lúcida, como minipeça do Maximecanismo Multidimensional Interassistencial."),
 "testemunho": C(lo("Testemunho",1930), "Quem **testemunha** a favor da iniquidade se candidata a transmigrado extrafísico."),
 "trintao-sem-duplista": C(lo("Duplista",675), "O **duplista** representa a Humanidade e a Para-Humanidade para o outro duplista; nele está sintetizada a Humanidade que se deve assistir."),
 "ato-clandestino": C(src("Homo sapiens pacificus","hsp","cap. 88",251), "Os acobertamentos mais prejudiciais geram interprisões grupocármicas multisseculares — p. ex. o sepultamento clandestino, dissimulado."),
}

REL = {
 "adversario-ideologico": [A+" — combatente das ideias evolutivas no convívio", "[[antagonismo]] · [[grupocarma]]"],
 "aglutinacao-interconsciencial": [A+" — unir pessoas para o mesmo objetivo evolutivo", "[[energia-consciencial]] · [[interassistencialidade]]"],
 "ajudante-de-algoz": [A+" — papel patológico no convívio", "[[cosmoetica]] · [[grupocarma]]"],
 "amigo-comum": [A+" — interface social potencializadora", "[[circulo-de-relacoes]] · [[interassistencialidade]]"],
 "amizade-evitavel": [A+" — convívio nefasto a evitar", "[[convivencia-nociva]] · [[companhia-constrangedora]]"],
 "amizade-interativa": [A+" — afeição recíproca teática", "[[amizade-rarissima]] · [[reciprocidade]]" if False else "[[amizade-rarissima]] · [[senso-de-fraternidade]]"],
 "amizade-rarissima": [A+" — amizade = autodiscernimento", "[[amizade-interativa]] · [[autodiscernimento]]"],
 "animador-consciencial": [A+" — conscin sempre disposta a animar o grupo", "[[interassistencialidade]] · [[entrevista-evolutiva]]"],
 "antagonismo-imitacao-evitacao": [A+" — acertar entre exemplos dignos e indignos", "[[imitacao-individual]] · [[evitacao-da-evitacao]]"],
 "anticonscienciologista": [A+" — posicionamento convicto contra a Conscienciologia", "[[adversario-ideologico]] · [[conscin-problema]]"],
 "antipodia-consciencial": [A+" — equilíbrio do microuniverso por opostos", "[[binomio-admiracao-discordancia]] · [[coniunctio]]"],
 "apoiante": [A+" — conscin/consciex apoiadora", "[[interassistencialidade]] · [[amparador]]" if False else "[[interassistencialidade]]"],
 "ato-clandestino": [A+" — ação às escondidas no convívio", "[[cosmoetica]] · [[grupocarma]]"],
 "benemerito-urbano": [A+" — personagem inesquecível da convivência urbana", "[[circulo-de-relacoes]] · [[holopensene]]"],
 "binomio-admiracao-discordancia": [A+" — união inteligente dos contrários", "[[universalismo]] · [[megafraternidade]] · [[antipodia-consciencial]]"],
 "binomio-autoconformismo-autoinconformismo": [A+" — ambivalência conformismo/inconformismo", "[[reciclagem-intraconsciencial]] · [[antipodia-consciencial]]"],
 "biparticao-de-raciocinio": [A+" — conduta dúbia/ambivalente no convívio", "[[binomio-autoconformismo-autoinconformismo]] · [[cosmoetica]]"],
 "carga-da-convivialidade": [A+" — natureza do período de convívio", "[[convivencia-nociva]] · [[plenitude-convivencial]]"],
 "casal-incompleto": [A+" — par sem intimidade plena", "[[dupla-evolutiva]] · [[trintao-sem-duplista]]"],
 "circulo-de-relacoes": [A+" — grupo social cultivado", "[[companhia-eletiva]] · [[amigo-comum]]"],
 "coedes": [A+" — coexistência desvinculada harmônica", "[[plenitude-convivencial]] · [[cosmoetica]]"],
 "cognopoliologia": [A+" — ciência da Cognópolis (bairro da cognição)", "[[interassistencialidade]] · [[universalismo]]"],
 "coloquialismo": [A+" — tom coloquial da expressão no convívio", "[[comunicologia]]" if False else "[[conduta-cosmoetica]]"],
 "companhia-constrangedora": [A+" — presença desagradável no convívio", "[[amizade-evitavel]] · [[convivencia-nociva]]"],
 "companhia-eletiva": [A+" — companhia escolhida no convívio", "[[circulo-de-relacoes]] · [[amizade-rarissima]]"],
 "comunidade-conscienciologica-cosmoetica-internacional": [A+" — comunidade da CCCI", "[[universalismo]] · [[megafraternidade]]"],
 "conduta-cosmoetica": [A+" — modo de agir cosmoético no convívio", "[[cosmoetica]] · [[megafraternidade]]"],
 "coniunctio": [A+" — união contínua dos opostos", "[[antipodia-consciencial]] · [[binomio-admiracao-discordancia]]"],
 "conscin-convencional": [A+" — vida assentada no trivial", "[[conscin-problema]] · [[reciclagem-intraconsciencial]]"],
 "conscin-problema": [A+" — pessoa complicada nas relações", "[[companhia-constrangedora]] · [[anticonscienciologista]]"],
 "convivencia-nociva": [A+" — convívio antievolutivo", "[[amizade-evitavel]] · [[companhia-constrangedora]]"],
 "dependencia-indireta": [A+" — dependência atuando de modo indireto", "[[grupocarma]] · [[reciclagem-intraconsciencial]]"],
 "desamarracao": [A+" — desfazer amarras do convívio", "[[desenredamento]] · [[reciclagem-intraconsciencial]]"],
 "desenredamento": [A+" — desfazer enredamentos do convívio", "[[desamarracao]] · [[reciclagem-intraconsciencial]]"],
 "dupla-noturna": [A+" — par orientado ao mesmo propósito noturno", "[[dupla-evolutiva]] · [[fauna-humana-noturna]]"],
 "elenco-da-conscienciologia": [A+" — conjunto de conscins e consciexes voluntárias", "[[interassistencialidade]] · [[megafraternidade]]"],
 "elogio-controvertivel": [A+" — elogio como heterocrítica ambígua", "[[conduta-cosmoetica]] · [[testemunho]]"],
 "entrevista-evolutiva": [A+" — encontro ajustado para fins evolutivos", "[[relacao-transformadora]] · [[interassistencialidade]]"],
 "estimulo-extrapauta": [A+" — agente inesperado que incita a evolução", "[[interassistencialidade]] · [[surpreendencia]]"],
 "evitacao-da-evitacao": [A+" — eliminar a evitação emocional", "[[antagonismo-imitacao-evitacao]] · [[reciclagem-intraconsciencial]]"],
 "exposicao-publica": [A+" — condição social notória", "[[omniexposicao]] · [[status]]"],
 "fauna-humana-noturna": [A+" — pessoas notívagas integradas à noite", "[[dupla-noturna]] · [[convivencia-nociva]]"],
 "fidus-achates": [A+" — amigo fiel e confiável", "[[amizade-rarissima]] · [[companhia-eletiva]]"],
 "fonte-de-controle": [A+" — origem do controle no convívio", "[[inducao-interconsciencial]] · [[dependencia-indireta]]"],
 "fusao-social": [A+" — convivialidade plena da megafraternidade", "[[megafraternidade]] · [[universalismo]]"],
 "imitacao-individual": [A+" — imitar determinada personalidade", "[[antagonismo-imitacao-evitacao]] · [[licao-de-vida]]"],
 "inducao-interconsciencial": [A+" — influenciar/sugerir a outra consciência", "[[fonte-de-controle]] · [[interassistencialidade]]"],
 "interassistenciologia": [A+" — ciência da interassistência", "[[interassistencialidade]] · [[megafraternidade]]"],
 "intersubjetividade": [A+" — comunicação entre consciências individuais", "[[dupla-evolutiva]] · [[relacao-conscin-consciex]]"],
 "licao-de-vida": [A+" — exemplo existencial inspirador", "[[imitacao-individual]] · [[conduta-cosmoetica]]"],
 "mirmidone": [A+" — seguidor que executa ordens sem questionar", "[[ajudante-de-algoz]] · [[dependencia-indireta]]"],
 "omniexposicao": [A+" — exposição onipresente e inevitável", "[[exposicao-publica]] · [[interassistencialidade]]"],
 "penduricalho-pessoal": [A+" — adorno/funcionalidade social", "[[exposicao-publica]] · [[status]]"],
 "permutabilidade-interconsciencial": [A+" — convívio ideal de troca lúcida", "[[reaproximacao-interconsciencial]] · [[interassistencialidade]]"],
 "plenitude-convivencial": [A+" — coexistência plena", "[[carga-da-convivialidade]] · [[fusao-social]]"],
 "profissional-dificultoso": [A+" — convívio profissional árduo", "[[conscin-problema]] · [[companhia-constrangedora]]"],
 "reaproximacao-interconsciencial": [A+" — reaproximar desavindos", "[[permutabilidade-interconsciencial]] · [[grupocarma]]"],
 "reclusao-voluntaria": [A+" — afastamento do convívio", "[[convivencia-nociva]] · [[omniexposicao]]"],
 "relacao-conscin-consciex": [A+" — trato vivencial conscin↔consciex", "[[intersubjetividade]] · [[consciex]]"],
 "relacao-transformadora": [A+" — contato que transforma", "[[entrevista-evolutiva]] · [[licao-de-vida]]"],
 "relevo-particular": [A+" — importância dada a personalidades", "[[companhia-eletiva]] · [[circulo-de-relacoes]]"],
 "rota-de-colisao": [A+" — trajetórias convivenciais em choque", "[[antagonismo]] · [[convivencia-nociva]]"],
 "senso-de-fraternidade": [A+" — afetividade teática harmoniosa", "[[megafraternidade]] · [[fusao-social]]"],
 "status": [A+" — posição/condição social", "[[exposicao-publica]] · [[interassistencialidade]]"],
 "surpreendencia": [A+" — o inesperado no convívio", "[[estimulo-extrapauta]]"],
 "testemunho": [A+" — ato de testemunhar/depor", "[[elogio-controvertivel]] · [[cosmoetica]]"],
 "trintao-sem-duplista": [A+" — homem sem parceira de dupla", "[[casal-incompleto]] · [[dupla-evolutiva]]"],
}

# limpeza dos placeholders False
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
