# -*- coding: utf-8 -*-
ESP = "Mentalsomatologia"
A = "[[mentalsoma]]"

def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "abstracao": lo("Abstração",46,"*Abstração: autodistração silenciosa.* (Há a abstração fixada, positiva, e a dispersiva, negativa.)"),
 "achega-matematica": lo("Achado",52,"*Achado é achega. Achega é achado.*"),
 "aperitivo-intelectual": src("Homo sapiens reurbanisatus","hsr","cap. 4",122,"A expressão *aperitivo intelectual* é neologismo técnico da Mentalsomática: ler orelhas, contracapa, início da introdução para antever a obra."),
 "aquecimento-neuronal": src("Homo sapiens reurbanisatus","hsr","cap. 6",122,"A expressão *aquecimento neuronial* é neologismo técnico da Mentalsomática: preparar antecipadamente os 2 hemisférios cerebrais para o trabalho intelectual."),
 "atencao-dividida": lo("Atenção",171,"A *criança* tem atenção saltuária; a **conscin vulgar**, atenção comum monofixada; o ***erudito***, atenção dividida, multifixada, cosmovisiológica."),
 "atencao": lo("Atenção",171,"*Atenção: buril mnemônico.* Inexiste concentração mental sem atenção."),
 "ato-mentalsomatico": lo("Serenão",1812,"O ato de acolhimento assistencial do Ser Serenão é especificamente mentalsomático."),
 "atributo-consciencial": lo("Atributo",177,"Somente é **atributo evoluído** da consciência aquela sua postura sem quaisquer laivos dos instintos."),
 "autenciclopedia": src("Homo sapiens pacificus","hsp","cap. 221",571,"Sob a ótica da Mentalsomática, o autodiscernimento é a estrutura da sabedoria, reunindo dezenas de realidades intraconscienciais — base da autenciclopédia pessoal."),
 "autorado-holocarmico": lo("Autorado",276,"Ante o *trinômio prole-obras-autorado*, o que mais perpetua a presença é a **obra-prima** do autorado."),
 "autorado": lo("Autorado",276,"O receio da conscin de se expor à crítica, gerado pelo orgulho, é o maior travão ao desenvolvimento do **autorado.**"),
 "autossuficiencia-intelectual": lo("Autossuficiência",301,"A autoconfiança e a autossuficiência tendem, paradoxalmente, a eliminar toda **vaidade.**"),
 "balanco-mentalsomatico": lo("Pensenografia",1528,"Escreva tudo o que ocorre de modo insólito e promova o balanço anual dos pensenes grafados — veja o que fazer com o seu **acervo mentalsomático.**"),
 "banco-de-dados": lo("Banco",324,"- \"Em seu **banco de dados** predomina a verdade ou a mentira?\""),
 "bibliofilia": lo("Insulsidade",1068,"A **bibliofilia** da conscin, quando *leitora estéril*, é um amor insulso."),
 "bibliofobia": src("Homo sapiens reurbanisatus","hsr","cap. 61",191,"Bibliofilia / bibliofobia integram o conteúdo *Mentalsomática* dos Cursos Intermissivos."),
 "bibliologia": dac("Assinvexologia",225,"A bibliofilia está no cerne útil da Bibliologia; a biblioteca faz pensar no valor cronológico das experiências e leituras."),
 "bibliotafio": lo("Bibliotáfio",340,"Todos os **livros antigos** e raros do bibliotáfio exumam as realidades do passado."),
 "biblioteca": lo("Biblioteca",340,"*Biblioteca: Medicina Mentalsomática.* A **biblioteca** é a creche dos *pensenes* da Humanidade."),
 "casa-do-intelecto": src("Homo sapiens pacificus","hsp","cap. 52",183,"Consoante a Evoluciologia, não há elevação intelectual sem Cosmoética; o *intelecto belicista* ainda vigora próximo do intelecto fetal."),
 "ciclo-mentalsomatico": src("200 Teáticas da Conscienciologia","200teat","cap. 32",52,"Pela conscienciometria, a existência do ciclo mentalsomático é a razão de ser de múltiplas posturas conscienciológicas."),
 "compreensao-da-conscienciologia": lo("Conscienciologia",496,"A real Teaticologia Conscienciológica atua quando há compreensão, pela conscin intermissivista, da essência dos princípios conscienciológicos."),
 "conceito": lo("Conceito",464,"Não existe conceito 100% virgem; todo conceito, até o **neoconceito**, é fundamentado em *retroconceito.*"),
 "contraponto-tecnico": lo("Contraponto",517,"A **criatividade** começa na *cópia contrapontual*; a cópia simples é mera imitação."),
 "cosmossintese": lo("Cosmossíntese",539,"A **cosmossíntese** mais abrangente é a fundamentada no espaço sideral."),
 "desembaraco-intelectual": lo("Intelectual",1069,"A primeira função do intelectual é ordenar a **autopensenidade**; a segunda, disciplinar a *linguagem.*"),
 "escala-dos-autores-mentaissomaticos": dac("Paradoxologia",1149,"Há paradoxos mentaissomáticos: intelectuais veteranos, com múltiplas obras, mais predispostos a revisões laboriosas dos próprios textos."),
 "esquete-onirica": src("Projeciologia","proj","cap. 94",220,"As imagens oníricas têm 7 características: vivacidade, mobilidade, intemporalidade, inespacialidade, intimidade, irracionalidade e vivencialidade."),
 "eunuco-intelectual": lo("Analfabeto",101,"*Analfabeto: eunuco intelectual.* O pior analfabeto é o indivíduo que tem preguiça de ler."),
 "evento-mentalsomatico": lo("Evento",793,"Prefira sempre participar de evento que busque algum **neoconhecimento** fora do ramerrame."),
 "exercitacao-neuronal": lo("Cerebrologia",395,"Todo **excesso** de alimentação e exercitação somática influi no cérebro."),
 "grupo-de-neoideias": lo("Neoideias",1348,"As **neoideias** geram neofatos e os *neofatos* geram neoideias, em alternância contínua que sustenta a evolução lúcida."),
 "horario-nobre": lo("Horário",984,"Sem **horário pessoal**, a vida não rende. Há tempo para velar e tempo para descansar."),
 "ideia-nuculanea": lo("Ideia",995,"O **feto da ideia**, ou hipótese, não é a ideia madura, ou teoria."),
 "ideia-original": src("700 Experimentos da Conscienciologia","700exp","cap. 34",98,"A ideia original — *hiperpensene* — é a representação mental de algo, aquisição de informação nova; pode ser concepção genial, descoberta ou invenção inédita."),
 "imagistica": lo("Imagística",1012,"O mais inteligente é a **domesticação da imaginação.**"),
 "inatividade-intelectual": src("Temas da Conscienciologia","temas","cap. 37",85,"O incompléxis resulta da inatividade da conscin imobilizada."),
 "inteleccao": lo("Intelecção",1069,"Com o emprego da **intelecção**, todas as questões ficam mais claras — ato de entender, conceber e compreender."),
 "interacao-essencia-acidente": src("200 Teáticas da Conscienciologia","200teat","cap. 50",70,"O *confor* (conteúdo + forma) é a interação inteligente da ideia/essência com a apresentação/linguagem nos processos da comunicação interconsciencial."),
 "intraconscienciologia": dac("Intraconscienciologia",849,"A Eletronótica busca eliminar a subjetividade para ficar só com a objetividade — valor malinterpretado da Intraconscienciologia."),
 "neociencia-conscienciologica": lo("Minidissidentes",1302,"O momento ímpar do movimento centrípeto da CCCI, na instalação da Neociência Conscienciológica neste Planeta, será sentido pelos minidissidentes."),
 "otimismo-racional": lo("Otimismo",1419,"A condição otimista mais expressiva e rentável é a da **conscin anciã.**"),
 "paradoxo-da-conscienciologia": lo("Paradoxo",1455,"A **evolução do mentalsoma** apresenta o grande paradoxo: só é possível simplificar a ignorância pela complexificação do conhecimento."),
 "pico-maximo-da-inteligencia": lo("Autolucidez",243,"O pico máximo da **autolucidez** é o maior conselheiro da consciência."),
 "politica-do-autorado-conscienciologico": lo("Conscienciografia",488,"O megafoco do autorado conscienciológico é a posteridade, a partir do **autorrevezamento multiexistencial.**"),
 "principio-da-descrenca": lo("Descrença",604,"O ***princípio da descrença*** (PD) é o mesmo princípio da incredulidade antigo; faz bem a todas as pessoas, sem exceção."),
 "principio-organizador-dos-saberes": lo("Organizadores",1409,"O paracérebro organiza a Paragenética; a Paragenética organiza o mentalsoma; o mentalsoma organiza o psicossoma — cadeia dos princípios organizadores."),
 "priorizacao-mentalsomatica": lo("Priorização",1628,"A pessoa vale o **percentual da priorização** evolutiva dos seus esforços."),
 "refutaciologia": lo("Refutaciologia",1717,"Usar o negativo como positivo revela falta de **discernimento**; a refutação cosmoética exige debate e heterocrítica honestos."),
 "ricochete-intelectivo": lo("Ricochete",1768,"Todo **mal** tem o ricochete ou revertério, sustentado pela *Lei de Causa e Efeito.*"),
 "ritmo-mentalsomatico": lo("Ritmo",1773,"Quando a conscin impõe ritmo cosmoético aos seus **pensenes**, toda a existência se organiza evolutivamente."),
 "saturacao-intelectiva": lo("Conscienciografologia",489,"Quando a conscin escritora não alcança a cosmovisão intelectiva, ocorre saturação e aumenta a probabilidade de erros ínfimos."),
 "sintese": lo("Síntese",1841,"*Síntese: digesto intelectivo. Autevolução é síntese.*"),
 "sutileza-conscienciologica": lo("Sutileza",1882,"Não se esqueça da **sutileza**: quem escreve e lê é muito diferente de quem lê e escreve."),
 "taxologia-do-conhecimento": src("Homo sapiens reurbanisatus","hsr","cap. 200",489,"Há 2 categorias de conhecimento: 1. Inútil (morto, mero peso intelectivo); 2. Produtivo (vivo, motor em funcionamento evolutivo)."),
 "topico-intelectivo": dac("Subtitulologia",1368,"O subtítulo é a palavra-chave do tópico, síntese do conteúdo identificado do parágrafo — exige atenção do redator e labor intelectivo."),
 "troca-intelectual": lo("Troca",1968,"A conscin mais lúcida parapsiquicamente troca as *férias laborais* do sono pelos trabalhos assistenciais da Projetabilidade Lúcida."),
 "turno-intelectual": lo("Flexibilidade",877,"Manter a vida intelectual junto da vida social exige maleabilidade e compensação por turno e por dia de trabalho, garantindo produtividade."),
 "verpon-motivadora": lo("Verpon",2003,"*Verpon: realidade uniparacerebral.* A verpon é o rolo compressor da **hiperacuidade.**"),
 "autodiscernimento-afetivo": src("Homo sapiens pacificus","hsp","cap. 21",108,"A vida afetivo-sexual ideal há de ser sempre embasada nos princípios do paracorpo do autodiscernimento."),
 "antilogismo": src("Homo sapiens pacificus","hsp","cap. 236",659,"Entre as 100 anteposições dos grupos nosográficos (atrasos evolutivos) figuram as contradições lógicas — terreno do antilogismo."),
}

# Relações: anchor + vizinhos temáticos
def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "abstracao": R("apreender a perspectiva separada do todo","[[sintese]] · [[conceito]] · [[inteleccao]]"),
 "achega-matematica": R("aporte que enriquece o argumento","[[ideia-nuculanea]] · [[contraponto-tecnico]]"),
 "antilogismo": R("argumento de conclusão contraditória","[[refutaciologia]] · [[conceito]]"),
 "aperitivo-intelectual": R("técnica de pré-leitura da obra","[[bibliofilia]] · [[nutricao-informacional]]"),
 "aquecimento-neuronal": R("preparar os hemisférios para o trabalho","[[exercitacao-neuronal]] · [[ritmo-mentalsomatico]]"),
 "atencao-dividida": R("atenção multifixada cosmovisiológica","[[atencao]] · [[hiperacuidade]]"),
 "atencao": R("concentração da mente em algo","[[atencao-dividida]] · [[limpidez-mental]]"),
 "ato-mentalsomatico": R("ação raciocinada a partir do mentalsoma","[[evento-mentalsomatico]] · [[autodiscernimento]]"),
 "atributo-consciencial": R("capacidade/faculdade da consciência","[[atencao]] · [[inteleccao]] · [[imagistica]]"),
 "autenciclopedia": R("acervo pessoal de todos os saberes","[[banco-de-dados]] · [[taxologia-do-conhecimento]]"),
 "autodiscernimento-afetivo": R("discernimento aplicado às emoções","[[autodiscernimento]] · [[priorizacao-mentalsomatica]]"),
 "autorado-holocarmico": R("autorado a serviço da holocarma","[[autorado]] · [[politica-do-autorado-conscienciologico]] · [[autorrevezamento-multiexistencial]]"),
 "autorado": R("condição/exercício do autor","[[autorado-holocarmico]] · [[conscienciografia]]"),
 "autossuficiencia-intelectual": R("haurir neoideias por si","[[grupo-de-neoideias]] · [[ideia-original]]"),
 "avanco-mentalsomatico": R("escancarar caminho a neoideias sadias","[[grupo-de-neoideias]] · [[verpon-motivadora]]"),
 "balanco-mentalsomatico": R("autodemonstração analítica do estado intelectivo","[[pico-maximo-da-inteligencia]] · [[priorizacao-mentalsomatica]]"),
 "banco-de-dados": R("coleção organizada de dados persistentes","[[autenciclopedia]] · [[nutricao-informacional]]"),
 "bibliofilia": R("amor aos livros e artefatos do saber","[[bibliofobia]] · [[biblioteca]] · [[bibliologia]]"),
 "bibliofobia": R("aversão aos livros","[[bibliofilia]] · [[inatividade-intelectual]]"),
 "bibliologia": R("ciência do livro","[[biblioteca]] · [[bibliotafio]] · [[bibliofilia]]"),
 "bibliotafio": R("guarda de obras raras","[[biblioteca]] · [[bibliologia]]"),
 "biblioteca": R("medicina mentalsomática (creche dos pensenes)","[[bibliologia]] · [[bibliotafio]] · [[casa-do-intelecto]]"),
 "casa-do-intelecto": R("holopensene das ideias","[[biblioteca]] · [[horario-nobre]]"),
 "ciclo-mentalsomatico": R("sequência regular da produção intelectiva","[[ritmo-mentalsomatico]] · [[turno-intelectual]]"),
 "coletivo-mentalsomatico": R("conjunto de realidades mentaissomáticas","[[grupo-de-neoideias]] · [[interrelacoes-interdisciplinares]]"),
 "compreensao-da-conscienciologia": R("compreender os princípios conscienciológicos","[[principio-da-descrenca]] · [[sutileza-conscienciologica]]"),
 "conceito": R("produto da faculdade de conceber","[[abstracao]] · [[sintese]] · [[suma-conceitual]]"),
 "contraponto-tecnico": R("temas contrastantes entrelaçados","[[interacao-essencia-acidente]] · [[ricochete-intelectivo]]"),
 "cosmossintese": R("síntese última do pesquisado","[[sintese]] · [[principio-organizador-dos-saberes]]"),
 "desembaraco-intelectual": R("fluência avançada da cognição","[[inteleccao]] · [[turno-intelectual]]"),
 "designacao": R("ato de nomear/discernir","[[conceito]] · [[taxologia-do-conhecimento]]"),
 "escala-dos-autores-mentaissomaticos": R("classificação técnica dos autores","[[autorado]] · [[politica-do-autorado-conscienciologico]]"),
 "esquete-onirica": R("vivência intelectiva em estado alterado","[[imagistica]] · [[limpidez-mental]]"),
 "eunuco-intelectual": R("conscin neutralizada intelectualmente","[[inatividade-intelectual]] · [[bibliofobia]]"),
 "evento-mentalsomatico": R("ocorrência intelectiva do mentalsoma","[[ato-mentalsomatico]] · [[ideia-original]]"),
 "exercitacao-neuronal": R("uso teático e profilático dos neurônios","[[aquecimento-neuronal]] · [[ritmo-mentalsomatico]]"),
 "grupo-de-neoideias": R("agrupamento de constructos novos","[[avanco-mentalsomatico]] · [[autossuficiencia-intelectual]] · [[ideia-original]]"),
 "horario-nobre": R("período eleito para o trabalho intelectual","[[ritmo-mentalsomatico]] · [[turno-intelectual]]"),
 "ideia-nuculanea": R("concepção com muitas sementes","[[ideia-original]] · [[achega-matematica]]"),
 "ideia-original": R("hiperpensene; aquisição de informação nova","[[grupo-de-neoideias]] · [[verpon-motivadora]] · [[ideia-nuculanea]]"),
 "imagistica": R("poder da imaginação/imagem mental","[[esquete-onirica]] · [[atributo-consciencial]]"),
 "inatividade-intelectual": R("inércia da cognição (incompléxis)","[[bibliofobia]] · [[eunuco-intelectual]]"),
 "inteleccao": R("elaborar pensamento com faculdades complexas","[[atencao]] · [[conceito]] · [[desembaraco-intelectual]]"),
 "interacao-essencia-acidente": R("confor: conteúdo × forma","[[contraponto-tecnico]] · [[conceito]]"),
 "interrelacoes-interdisciplinares": R("conexões entre Ciências","[[coletivo-mentalsomatico]] · [[taxologia-do-conhecimento]]"),
 "intraconscienciologia": R("ciência centrada no intraconsciencial","[[mentalsoma]]" if False else "[[autodiscernimento]] · [[principio-da-descrenca]]"),
 "limpidez-mental": R("clareza/nitidez da autopensenidade","[[atencao]] · [[inteleccao]]"),
 "neociencia-conscienciologica": R("a neociência da consciência","[[compreensao-da-conscienciologia]] · [[sutileza-conscienciologica]]"),
 "nutricao-informacional": R("recepção de informações que alimentam","[[banco-de-dados]] · [[aperitivo-intelectual]]"),
 "otimismo-racional": R("encarar pelo lado melhor, com razão","[[atributo-consciencial]] · [[verpon-motivadora]]"),
 "paradoxo-da-conscienciologia": R("o que parece contraditório e é verdadeiro","[[sutileza-conscienciologica]] · [[principio-da-descrenca]]"),
 "parepistemologia": R("ciência da paraepistemologia","[[neociencia-conscienciologica]] · [[principio-da-descrenca]]"),
 "pico-maximo-da-inteligencia": R("auge da agudez mental","[[hiperacuidade]] · [[balanco-mentalsomatico]]"),
 "politica-do-autorado-conscienciologico": R("procedimentos do autorado para a posteridade","[[autorado-holocarmico]] · [[autorrevezamento-multiexistencial]] · [[conscienciografia]]"),
 "presumibilidade": R("conjectura por suposição/hipótese","[[ideia-nuculanea]] · [[conceito]]"),
 "principio-da-descrenca": R("não acredite, experimente (PD)","[[neociencia-conscienciologica]] · [[refutaciologia]]"),
 "principio-organizador-dos-saberes": R("cadeia dos princípios organizadores","[[cosmossintese]] · [[taxologia-do-conhecimento]]"),
 "priorizacao-mentalsomatica": R("colocar o autodiscernimento em primeiro","[[autodiscernimento]] · [[hiperacuidade]] · [[autodiscernimento-afetivo]]"),
 "refutaciologia": R("ciência da refutação e heterocrítica","[[principio-da-descrenca]] · [[antilogismo]]"),
 "ricochete-intelectivo": R("rebote imediato de uma ideia","[[contraponto-tecnico]] · [[verpon-motivadora]]"),
 "ritmo-mentalsomatico": R("administrar o ritmo da produção intelectiva","[[ciclo-mentalsomatico]] · [[horario-nobre]] · [[turno-intelectual]]"),
 "saturacao-intelectiva": R("repetição didática dos temas essenciais","[[ritmo-mentalsomatico]] · [[sutileza-conscienciologica]]"),
 "sintese": R("reunião de partes diferentes num todo","[[abstracao]] · [[cosmossintese]] · [[suma-conceitual]]"),
 "suma-conceitual": R("trabalho amplo sobre um conceito","[[conceito]] · [[sintese]]"),
 "sutileza-conscienciologica": R("caráter sutil dos conceitos evoluídos","[[paradoxo-da-conscienciologia]] · [[neociencia-conscienciologica]]"),
 "taxologia-do-conhecimento": R("classificação da natureza do conhecimento","[[principio-organizador-dos-saberes]] · [[interrelacoes-interdisciplinares]]"),
 "topico-intelectivo": R("trecho preciso destacado no argumento","[[conceito]] · [[contraponto-tecnico]]"),
 "troca-intelectual": R("permutabilidade cognitiva entre conscins","[[nutricao-informacional]] · [[interrelacoes-interdisciplinares]]"),
 "turno-intelectual": R("reação em cadeia dos autopensenes criativos","[[ritmo-mentalsomatico]] · [[horario-nobre]] · [[ciclo-mentalsomatico]]"),
 "verpon-motivadora": R("verpon que estimula a conscin estafada","[[verpon]] · [[neoverpon]] · [[ideia-original]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
