# -*- coding: utf-8 -*-
ESP = "Autevoluciologia"
A = "[[autevolucao]]"
def lo(v,p,t): return ("Léxico de Ortopensatas", t, f"Léxico de Ortopensatas, p. {p}.", f"`corpus/lo.json` — [[lexico-de-ortopensatas|Léxico de Ortopensatas]], verbete *{v}*, p. {p}.")
def dac(v,p,t): return ("Dicionário de Argumentos da Conscienciologia", t, f"Dicionário de Argumentos da Conscienciologia, verbete *{v}*, p. {p}.", f"`corpus/dac.json` — [[dicionario-de-argumentos-da-conscienciologia|DAC]], verbete *{v}*, p. {p}.")
def src(book,file,cap,p,t): return (book, t, f"{book}, {cap}, p. {p}.", f"`corpus/{file}.json` — {book}, {cap}, p. {p}.")

CONV = {
 "autavaliacao-evolutiva": lo("Autavaliação",183,"Pergunta que sintetiza o *Conscienciograma*: — Você é a pessoa que vive fazendo o *certo*, ou o indivíduo que vive criticando o *errado*?"),
 "autocomprovacao": lo("Encapsulamento",715,"Quem vivencia o encapsulamento energético promovido por amparador jamais deixa de pensar na extrafisicalidade, pela inexorável autocomprovação de sinaléticas."),
 "autoconquista": lo("Fins",875,"Somente os *bons meios* são capazes de sustentar a autoconquista dos **bons fins.**"),
 "autodominio-da-conquista": lo("Autodomínio",234,"*Façanha íntima* é alcançar o completismo da proéxis; **glória suprema** é alcançar o autodomínio consciencial com a Cosmoética Vivida."),
 "autoprevisao-existencial": lo("Autoprevisão",271,"Quem já vivenciou autorretrocognições e analisa criteriosamente a vida presente pode prever a própria trajetória — quem acerta a festa antecipadamente desfruta-a melhor."),
 "completude-consciencial": lo("Completude",448,"No caminho da evolução não existe **completude** sem alguma falta; a completude é indispensável."),
 "continuidade-extrafisica": lo("Recomeço",1704,"*Evolução é continuidade.*"),
 "exito": lo("Êxito",826,"O **êxito** sem arrogância é o único legítimo; a teoria do êxito fundamentado no dinheiro é a mais superficial e frustrante."),
 "fep-do-intermissivista": lo("FEP",869,"Pouco importa se a conscin aplica a técnica da invéxis ou da recéxis: o que vale sempre é a qualidade do **saldo da FEP.**"),
 "ficha-evolutiva-pessoal": lo("Exatidão",816,"Onde se encontra a maior **exatidão matemática** é na *Ficha Evolutiva Pessoal* (FEP)."),
 "fixacao-no-rentavel": lo("Modéstia",1315,"Em quaisquer instâncias evolutivas, a **modéstia** é sempre mais rentável do que a vaidade."),
 "ganho-evolutivo": lo("Poupança",1595,"*Poupança: maior ganho.*"),
 "garantia-evolutiva": lo("Garantia",902,"A razão da consciência e a verdade dos fatos sobrepairam a todos os eclipses impostos pelos néscios — esta é a garantia da Evoluciologia."),
 "imitacao-evolutiva": lo("Imitação",1014,"*Imitação: primeira protossabedoria.* (Observar quem está acima na escala evolutiva.)"),
 "integridade-consciencial": lo("Integridade",1069,"Você só alcança a integridade, a completude e a totalidade da personalidade em evolução a partir do **autodiscernimento parapsíquico**, multidimensional."),
 "inteligencia-evolutiva": lo("Inteligência",1073,"A verdadeira ***Inteligência Evolutiva*** é multidimensional; a consciência com IE tem a cosmovisão intrínseca."),
 "meta-optata": src("700 Experimentos da Conscienciologia","700exp","cap. 478",542,"Há 20 metas multidimensionais (autocrítica → autoconhecimento; autolucidez → estado da consciência contínua etc.)."),
 "modelo-contiguo": src("Homo sapiens pacificus","hsp","cap. 345",907,"Sob a Experimentologia, quem pesquisa a genialidade está no caminho contíguo à Serenologia."),
 "necessidade-evolutiva": lo("Ofiex",1384,"A ofiex, além de conquista evolutiva almejada, é uma **necessidade compulsória positiva** para a conscin ofiexista e seus assistidos."),
 "nulificacao-da-infancia": dac("Assinvexologia",227,"O inversor jovem está com a doença da juventude, que o tempo cura: o negócio é virar consciência e deixar de ser animal humano."),
 "objetivo-pessoal": lo("Objetivo",1372,"O **amor** é o objetivo da Duplologia e da Evoluciologia; a autotransafetividade é o objetivo da Megafraternologia."),
 "pertencimento-pessoal": dac("Automegatransposiciologia",350,"O nível hierárquico de cada consciência especifica a qualificação da FEP, no quadro geral do seu pertencimento autoconsciente ao grupo evolutivo."),
 "ponto-evolutivo": lo("Administração",60,"A pessoa mais inteligente, do ponto de vista evolutivo, é a administradora do próprio destino, de modo consciente e interassistencial."),
 "primado-evolutivo": src("Homo sapiens reurbanisatus","hsr","cap. 349",883,"O voluntariado cosmoético da Conscienciologia é o *primado do governo da autoconsciência.*"),
 "prioridade": lo("Prioridade",1627,"Quem identifica mais prioridade no **processo evolutivo** das consciências acerta mais na interassistencialidade."),
 "progressao-permanente": lo("Progressão",1645,"A **progressão da consciência** existe na razão direta da destruição da *sacralização das coisas.*"),
 "quintessencia-evolutiva": dac("Suprassumologia",1376,"A autocosmoconsciência pode ser considerada o pináculo ou a quintessência da experiência evolutiva."),
 "recorrencia": src("Homo sapiens pacificus","hsp","cap. 100",638,"A recorrência dos atos componentes dos grupos nosográficos faz os amparadores extrafísicos se afastarem do holopensene da conscin patológica."),
 "senso-de-urgencia": lo("Urgência",1979,"A *tarefa do esclarecimento* (tares) deve atender à urgência da consciência assistível: mais vale um *não* a tempo que um *sim* retardado."),
 "sintese-do-autoconscienciograma": lo("Síntese",1841,"A base do **conscienciês** é a síntese evolutiva; o maior talento do analista é a síntese depois da análise."),
 "status-momentosus": lo("Status",1863,"O *status* evolutivo maior é o gabarito da pessoa na interassistencialidade lúcida, como minipeça do Maximecanismo Multidimensional Interassistencial."),
 "trinomio-evolutivo": lo("Trinômio",1966,"A conscin lúcida sabe respirar com o *trinômio evolutivo vivência-observação-registro*, o tempo todo."),
 "viragem-autevolutiva": lo("Restauração",1743,"*Restauração: viragem autevolutiva.* O que atrai mais as consciexes amparadoras é a viragem da intenção evolutiva da conscin para melhor."),
 "personalidade-bem-formada": src("Manual da Dupla Evolutiva","dupla","cap. 11",48,"Não existe dupla evolutiva bem-formada com 2 conscins malcasadas na vida cotidiana — a personalidade bem formada é base da dupla."),
}
CONV = {k:v for k,v in CONV.items() if v}

def R(*xs): return [A+" — "+xs[0]] + list(xs[1:])
REL = {
 "autaplicacao-evolutiva": R("aplicar/reaplicar os recursos evolutivos","[[autorrendimento-evolutivo]] · [[filao-autevolutivo]]"),
 "autavaliacao-evolutiva": R("análise autocrítica do próprio nível","[[sintese-do-autoconscienciograma]] · [[autavaliacao-evolutiva]]" if False else "[[sintese-do-autoconscienciograma]] · [[nivel-desenvolvimental]]"),
 "autocomprovacao": R("comprovar por si os resultados","[[autavaliacao-evolutiva]] · [[ganho-evolutivo]]"),
 "autoconquista": R("consecução pessoal de feitos","[[neoconquista]] · [[autodominio-da-conquista]] · [[maxiconquista-atual]]"),
 "autodominio-da-conquista": R("governo pessoal pleno da conquista","[[autoconquista]] · [[integridade-consciencial]]"),
 "autoprevisao-existencial": R("prognóstico da meta máxima existencial","[[autoavaliacao-evolutiva]]" if False else "[[meta-optata]] · [[objetivo-pessoal]]"),
 "autorrendimento-evolutivo": R("valor produzido pelo desempenho sadio","[[ganho-evolutivo]] · [[autaplicacao-evolutiva]]"),
 "candidatura-evolutiva": R("apresentar-se a novo patamar evolutivo","[[viragem-autevolutiva]] · [[maxiconquista-atual]]"),
 "completude-consciencial": R("excelência evolutiva máxima na vida","[[neoconquista]] · [[integridade-consciencial]]"),
 "conscin-transcendente": R("conscin de inteligência transcendente","[[inteligencia-evolutiva]] · [[quintessencia-evolutiva]]"),
 "continuidade-extrafisica": R("continuidade da vida na extrafisicalidade","[[progressao-permanente]] · [[garantia-evolutiva]]"),
 "cronoevoluciologia": R("ciência do tempo na autevolução","[[ponto-evolutivo]] · [[senso-de-urgencia]]"),
 "directrix": R("norma de procedimento racional e justa","[[ponto-evolutivo]] · [[prioridade]]"),
 "evolucao-transparente": R("explicitação crescente da consciência","[[integridade-consciencial]] · [[progressao-permanente]]"),
 "exito": R("resultado feliz que enriquece a evolução","[[ganho-evolutivo]] · [[maxiconquista-atual]]"),
 "extensao-consciencial": R("expandir/ampliar a consciência","[[progressao-permanente]] · [[onicompetencia-consciencial]]"),
 "fep-do-intermissivista": R("FEP de quem concluiu o CI","[[ficha-evolutiva-pessoal]] · [[pertencimento-pessoal]]"),
 "ficha-evolutiva-pessoal": R("registro extrafísico do saldo evolutivo","[[fep-do-intermissivista]] · [[autavaliacao-evolutiva]]"),
 "filao-autevolutivo": R("rumo prioritário fixado na autevolução","[[autaplicacao-evolutiva]] · [[ponto-evolutivo]]"),
 "fixacao-no-rentavel": R("comportamento focado no evolutivamente rentável","[[ganho-evolutivo]] · [[prioridade]]"),
 "ganho-evolutivo": R("proveito cosmoético do ato acertado","[[autorrendimento-evolutivo]] · [[exito]]"),
 "garantia-evolutiva": R("trocar o finito pelo imperecível","[[continuidade-extrafisica]] · [[progressao-permanente]]"),
 "imitacao-evolutiva": R("observar quem está acima na escala","[[modelo-contiguo]] · [[inteligencia-evolutiva]]"),
 "integridade-consciencial": R("perfil íntegro pelo autodiscernimento","[[completude-consciencial]] · [[personalidade-bem-formada]]"),
 "inteligencia-evolutiva": R("capacidade de evoluir (IE multidimensional)","[[conscin-transcendente]] · [[quintessencia-evolutiva]] · [[ponto-evolutivo]]"),
 "interesse-transempresarial": R("vivência racional do interesse evolutivo grupal","[[pertencimento-pessoal]] · [[interesse-transempresarial]]" if False else "[[pertencimento-pessoal]] · [[objetivo-pessoal]]"),
 "legislador-evolutivo": R("conscin que delineia diretrizes evolutivas","[[directrix]] · [[inteligencia-evolutiva]]"),
 "maxiconquista-atual": R("arregimentar-se para o êxito da vida","[[autoconquista]] · [[neoconquista]] · [[exito]]"),
 "megaimprevisibilidade": R("dificuldade máxima de prever (pré-serenão)","[[autoprevisao-existencial]] · [[megaimprevisibilidade]]" if False else "[[autoprevisao-existencial]] · [[recorrencia]]"),
 "meta-optata": R("o fim atingido (resultado da meta)","[[objetivo-pessoal]] · [[autoprevisao-existencial]]"),
 "modelo-contiguo": R("consciência-modelo mais próxima","[[imitacao-evolutiva]] · [[referencia]]"),
 "necessidade-evolutiva": R("exigências impostas pelas Leis do Cosmos","[[garantia-evolutiva]] · [[primado-evolutivo]]"),
 "neoconquista": R("nova conquista com governo pessoal","[[autoconquista]] · [[maxiconquista-atual]]"),
 "nivel-desenvolvimental": R("condição exata no momento evolutivo","[[autavaliacao-evolutiva]] · [[ficha-evolutiva-pessoal]]"),
 "nulificacao-da-infancia": R("anular o ônus da infância (invéxis)","[[viragem-autevolutiva]] · [[personalidade-bem-formada]]"),
 "objetivo-pessoal": R("alvo primordial da existência","[[meta-optata]] · [[autoprevisao-existencial]] · [[prioridade]]"),
 "onicompetencia-consciencial": R("competência para qualquer situação","[[extensao-consciencial]] · [[completude-consciencial]]"),
 "paraconstructura": R("autoconstrução do constructo pessoal","[[integridade-consciencial]] · [[evolucao-transparente]]"),
 "parapolimaticologia": R("ciência do parapolimatismo","[[inteligencia-evolutiva]] · [[onicompetencia-consciencial]]"),
 "paraverbacao-evolutiva": R("conduta ideal da autoproéxis lúcida","[[autaplicacao-evolutiva]] · [[autorrendimento-evolutivo]]"),
 "personalidade-bem-formada": R("consciência madura, autolúcida, cosmoética","[[integridade-consciencial]] · [[completude-consciencial]]"),
 "pertencimento-pessoal": R("autodestinação ao grupo evolutivo","[[fep-do-intermissivista]] · [[ficha-evolutiva-pessoal]]"),
 "polaridade-extrema": R("condição de polaridade máxima","[[progressao-permanente]] · [[ser-estar]]"),
 "ponto-evolutivo": R("demarcação inteligente dos atos","[[prioridade]] · [[filao-autevolutivo]] · [[senso-de-urgencia]]"),
 "prevalencia-evolutiva": R("predomínio evolutivo vantajoso","[[prevalencia]] · [[primado-evolutivo]]"),
 "prevalencia": R("característica predominante/prioritária","[[prevalencia-evolutiva]] · [[prioridade]]"),
 "primado-evolutivo": R("a realidade posta em primeiro lugar","[[prioridade]] · [[necessidade-evolutiva]]"),
 "prioridade": R("a realidade mais relevante atendida primeiro","[[primado-evolutivo]] · [[ponto-evolutivo]] · [[objetivo-pessoal]]"),
 "progressao-permanente": R("progredir sem cessar","[[continuidade-extrafisica]] · [[evolucao-transparente]]"),
 "quintessencia-evolutiva": R("o essencial mais puro e refinado","[[conscin-transcendente]] · [[completude-consciencial]]"),
 "recorde-homeostatico": R("proeza sadia que aponta a melhor atuação","[[autorrendimento-evolutivo]] · [[ganho-evolutivo]]"),
 "recorrencia": R("repetição continuada da mesma operação","[[megaimprevisibilidade]] · [[recorde-homeostatico]]"),
 "referencia": R("reportar-se a uma realidade-modelo","[[modelo-contiguo]] · [[imitacao-evolutiva]]"),
 "senso-de-urgencia": R("julgar a urgência do tempo evolutivo","[[ponto-evolutivo]] · [[prioridade]]"),
 "ser-estar": R("condição ambígua ser/estar do intermissivista","[[status-momentosus]] · [[polaridade-extrema]]"),
 "sintese-do-autoconscienciograma": R("resultado da autoavaliação pelo conscienciograma","[[autavaliacao-evolutiva]] · [[ficha-evolutiva-pessoal]]"),
 "status-momentosus": R("modo de estar no momento evolutivo","[[ser-estar]] · [[nivel-desenvolvimental]]"),
 "trinomio-evolutivo": R("vivência-observação-registro","[[autavaliacao-evolutiva]] · [[autocomprovacao]]"),
 "viragem-autevolutiva": R("mudança profunda do patamar evolutivo","[[candidatura-evolutiva]] · [[nulificacao-da-infancia]]"),
}
for k,v in list(REL.items()):
    REL[k] = [x for x in v if x]
